import random
from datetime import datetime, timedelta
import string

USA_first_names_male = [
    "Liam", "Noah", "Oliver", "Theodore", "James", "Henry", "Mateo", "Elijah", 
    "Lucas", "William", "Benjamin", "Levi", "Ezra", "Sebastian", "Jack", 
    "Daniel", "Samuel", "Michael", "Ethan", "Asher", "John", "Hudson", "Luca", 
    "Leo", "Elias", "Owen", "Alexander", "Dylan", "Santiago", "Julian", "David", 
    "Joseph", "Matthew", "Luke", "Jackson", "Maverick", "Miles", "Wyatt", 
    "Thomas", "Isaac", "Jacob", "Mason", "Gabriel", "Anthony", "Carter", 
    "Logan", "Aiden", "Grayson", "Caleb", "Cooper", "Charles", "Roman", 
    "Josiah", "Ezekiel", "Thiago", "Isaiah", "Joshua", "Wesley", "Jayden", 
    "Bennett", "Christopher", "Nathan", "Angel", "Nolan", "Waylon", "Cameron", 
    "Brooks", "Andrew", "Beau", "Weston", "Rowan", "Adrian", "Lincoln", "Enzo", 
    "Ian", "Kai", "Christian", "Axel", "Aaron", "Theo", "Silas", "Walker", 
    "Jonathan", "Leonardo", "Everett", "Micah", "Ryan", "August", "Gael", 
    "Robert", "Jose", "Eli", "Jeremiah", "Luka", "Amir", "Jaxon", "Parker", 
    "Colton", "Myles", "Adam", "Atlas", "Xavier", "Easton", "Jordan", "Arthur", 
    "Landon", "Austin", "Dominic", "Adriel", "Damian", "Vincent", "River", 
    "Emiliano", "Jace", "Archer", "Lorenzo", "Jameson", "Nicholas", "Emmett", 
    "Milo", "Harrison", "Giovanni", "Carson", "George", "Kayden", "Jonah", 
    "Greyson", "Hunter", "Graham", "Luis", "Declan", "Sawyer", "Jasper", 
    "Ryder", "Carlos", "Connor", "Juan", "Matteo", "Dawson", "Calvin", "Leon", 
    "Dean", "Evan", "Nathaniel", "Diego", "Arlo", "Bryson", "Jason", "Malachi", 
    "Elliot", "Zion", "Emilio", "Ivan", "Hayden", "Stetson", "Jude", "Legend", 
    "Matias", "Callum", "Hayes", "Jett", "Cole", "Elliott", "Jesus", "Ace", 
    "Beckett", "Alan", "Beckham", "Jayce", "Braxton", "Jaxson", "Amari", 
    "Chase", "Rhett", "Max", "Charlie", "Felix", "Kingston", "Judah", "Antonio", 
    "Emmanuel", "Maxwell", "Ryker", "Alejandro", "Nicolas", "Barrett", "Jesse", 
    "Ashton", "Miguel", "Brayden", "Tyler", "Peter", "Camden", "Zachary", 
    "Tatum", "Kevin", "Andres", "Finn", "Justin", "Tucker", "Bentley", "Zayden", 
    "Messiah", "Abraham", "Alex", "Adonis", "Kaiden", "Timothy", "Knox", "Tate", 
    "Caden", "Ayden", "Nico", "Victor", "Maddox", "Xander", "Oscar", "Colter", 
    "Joel", "Abel", "Patrick", "Rafael", "Griffin", "Brody", "Jaziel", "Rory", 
    "Eithan", "Edward", "Riley", "Brandon", "Milan", "Richard", "Malakai", 
    "Ismael", "Kyrie", "Louis", "Elian", "Kairo", "Cohen", "Nash", "Grant", 
    "Callan", "Dallas", "Harvey", "Muhammad", "Mark", "Javier", "Karter", 
    "Zayn", "Crew", "Eric", "Simon", "Aziel", "Cyrus", "Gavin", "Marcus", 
    "Ronan", "Derek", "Avery", "Omar", "Lane", "Warren", "Lennox", "Paul", 
    "Blake", "Jeremy", "Tristan", "Lukas", "Steven", "Emerson", "Walter", 
    "Cade", "Ellis", "Otto", "Phoenix", "Colt", "Atticus", "Kaleb", "Israel", 
    "Tobias", "Holden", "Saint", "Romeo", "Kenneth", "Jorge", "Angelo", 
    "Remington", "Paxton", "Cody", "Finley", "Kayson", "Koa", "Kash", "Josue", 
    "Ares", "Hendrix", "Bryce", "Maximiliano", "Zyaire", "Reid", "Brian", 
    "Bodhi", "Cruz", "Kaden", "Bryan", "Zane", "Francisco", "Martin", "Brady", 
    "Casey", "Shepherd", "Aidan", "Baker", "Malcolm", "Jax", "Cash", "Clayton", 
    "Kohen", "Leonel", "Cristian", "Bowen", "Dante", "Ali", "Jaylen", "Orion", 
    "Briggs", "Jensen", "Dakota", "Preston", "Maximus", "Gideon", "Erick", 
    "Archie", "Colin", "Sonny", "Shiloh", "Mathias", "Ezequiel", "Sullivan", 
    "Joaquin", "Wade", "King", "Niko", "Damien", "Kade", "Bodie", "Dariel", 
    "Luciano", "Cayden", "Andre", "Manuel", "Fernando", "Colson", "Rhys", 
    "Cairo", "Anderson", "Kyler", "Onyx", "Ibrahim", "Cesar", "Travis", 
    "Santino", "Callahan", "Bradley", "Baylor", "Banks", "Russell", "Desmond", 
    "Killian", "Grady", "Rylan", "Sterling", "Kylo", "Eduardo", "Ricardo", 
    "Wells", "Stephen", "Zander", "Raymond", "Hector", "Eliam", "Edwin", 
    "Titus", "Iker", "Franklin", "Kamari", "Marco", "Spencer", "Julius", 
    "Khalil", "Marshall", "Wilder", "Jared", "Jaden", "Kashton", "Jay", 
    "Karson", "Mario", "Ari", "Remy", "Pedro", "Sergio", "Hugo", "Prince", 
    "Winston", "Pablo", "Forrest", "Augustus", "Kobe", "Oakley", "Daxton", 
    "Tadeo", "Sage", "Apollo", "Lawson", "Kian", "Solomon", "Chance", "Kayce", 
    "Raphael", "Reed", "Jake", "Frederick", "Armani", "Hank", "Nehemiah", 
    "Royal", "Kameron", "Malik", "Alijah", "Kane", "Dalton", "Lewis", "Noel", 
    "Benson", "Sean", "Clark", "Miller", "Kyle", "Kieran", "Sutton", "Fabian", 
    "Tanner", "Marcelo", "Rowen", "Isaias", "Zayne", "Nasir", "Raiden", 
    "Francis", "Bo", "Valentino", "Rome", "Damon", "Reece", "Esteban", "Edgar", 
    "Johnny", "Kylian", "Tyson", "Uriel", "Royce", "Cillian", "Koda", "Kyson", 
    "Eden", "Jalen", "Frank", "Conrad", "Jasiah", "Matthias", "Zaire", "Corbin", 
    "Asa", "Yusuf", "Erik", "Callen", "Kendrick", "Odin", "Brantley", "Rodrigo", 
    "Marcos", "Gianni", "Alexis", "Lucian", "Denver", "Sylas", "Andy", "Collin", 
    "Hezekiah", "Moshe", "Finnegan", "Ronin", "Atreus", "Adan", "Emanuel", 
    "Quinn", "Mack", "Leandro", "Rocco", "Ruben", "Ledger", "Azariah", 
    "Donovan", "Moses", "Kaizen", "Elio", "Leonidas", "Lawrence", "Tripp", 
    "Ariel", "Alonzo", "Kaison", "Lian", "Devin", "Rio", "Johnathan", "Ayaan", 
    "Gunner", "Jeffrey", "Philip", "Samson", "Moises", "Lucca", "Musa", 
    "Camilo", "Hamza", "Ridge", "Kolton", "Morgan", "Troy", "Kylan", "Amiri", 
    "Boone", "Makai", "Johan", "Bruce", "Dorian", "Gregory", "Pierce", "Roy", 
    "Drew", "Clay", "Caiden", "Enrique", "Jamir", "Leland", "Mohamed", 
    "Alessandro", "Deacon", "Augustine", "Dominick", "Roberto", "Kasen", 
    "Zain", "Jonas", "Emir", "Seth", "Saul", "Jamari", "Lionel", "Garrett", 
    "Jaiden", "Fletcher", "Scott", "Armando", "Cassius", "Kason", "Zachariah", 
    "Ford", "Soren", "Zaiden", "Allen", "Louie", "Ronald", "Alden", "Arturo", 
    "Caspian", "Rayan", "Major", "Arjun", "Colby", "Eliel", "Krew", "Ander", 
    "Kenzo", "Maximilian", "Memphis", "Nikolai", "Samir", "Ocean", "Anakin", 
    "Gerardo", "Keegan", "Maximo", "Mohammed", "Kaysen", "Julio", "Mohammad", 
    "Gunnar", "Shane", "Ozzy", "Zakai", "Sincere", "Jaime", "Albert", "Azriel", 
    "Izaiah", "Jaxton", "Raul", "Yosef", "Creed", "Rhodes", "Princeton", 
    "Porter", "Cassian", "Omari", "Tru", "Chosen", "Reese", "Jayceon", "Jayson", 
    "Jamie", "Reign", "Trevor", "Phillip", "Boston", "Kamden", "Crue", "Eliseo", 
    "Colsen", "Keanu", "Mauricio", "Salem", "Dario", "Dax", "Jase", "Shawn", 
    "Vicente", "Gustavo", "Danny", "Mylo", "Kyro", "Wilson", "Davis", "Jakari", 
    "Jakai", "Truett", "Hassan", "Chris", "Sam", "Brixton", "Kyaire", "Uriah", 
    "Azael", "Westley", "Rocky", "Peyton", "Sevyn", "Dilan", "Drake", "Zaid", 
    "Roland", "Dereck", "Braylen", "Harlan", "Taylor", "Riggs", "Ahmad", "Cal", 
    "Marvin", "Donald", "Leonard", "Nathanael", "Aarav", "Abdiel", "Kareem", 
    "Corey", "Emmitt", "Wylder", "Koen", "Junior", "Zyair", "Zayd", "Dustin", 
    "Wayne", "Ahmed", "Madden", "Quincy", "Bellamy", "Lachlan", "Layton", 
    "Amias", "Chaim", "Layne", "Mac", "Amos", "Briar", "Carmelo", "Aries", 
    "Bruno", "Houston", "Julien", "Trace", "Brock", "Yahya", "Conor", "Dennis", 
    "Duke", "Abram", "Jefferson", "Vincenzo", "Izan", "Lee", "Finnley", 
    "Brayan", "Raylan", "Enoch", "Avyaan", "Dexter", "Salvador", "Case", 
    "Misael", "Forest", "Nikolas", "Westin", "Braylon", "Clyde", "Ryland", 
    "Otis", "Tommy", "Zeke", "Yehuda", "Tomas", "Azrael", "Dutton", "Flynn", 
    "Chandler", "Idris", "Zamir", "Ambrose", "Franco", "Huxley", "Wes", 
    "Chozen", "Darius", "Valentin", "Alberto", "Magnus", "Roger", "Benicio", 
    "Brycen", "Marcel", "Ryatt", "Zahir", "Keith", "Rayden", "Jamison", "Teo", 
    "Skyler", "Blaze", "Cayson", "Hugh", "Yahir", "Cannon", "Yousef", "Bjorn", 
    "Noe", "Alonso", "Alvaro", "Evander", "Kenai", "Aurelio", "Jahmir", 
    "Lochlan", "Aron", "Harry", "Nelson", "Ray", "Alfredo", "Abdullah", "Aryan", 
    "Conner", "Lennon", "Bridger", "Westyn", "Jasiel", "Quentin", "Trey", 
    "Yael", "Alvin", "Casen", "Dakari", "Rex", "Damir", "Waylen", "Izael", 
    "Jeremias", "Kaiser", "Kolson", "Ben", "Kyree", "Tony", "Bode", "Jesiah", 
    "Eiden", "Jaxxon", "Jedidiah", "Remi", "Robin", "Santana", "Kyren", 
    "Landen", "Ezrah", "Murphy", "Castiel", "Boden", "Derrick", "Karim", 
    "Mustafa", "Rey", "Rudy", "Emery", "Ignacio", "Jettson", "Bear", "Edison", 
    "Ricky", "Ramon", "Anders", "Gage", "Guillermo", "Kolter", 
    "Quinton", "Axton", "Abner", "Alfred", "Darwin", "Rohan", "Lance", "Avi", 
    "Keaton", "Orlando", "Everest", "Jagger", "Elisha", "Heath", "Jones", 
    "Thaddeus", "Allan", "Cason", "Douglas", "Issac", "Kenji", "Matheo", "Ty", 
    "Asaiah", "Jimmy", "Arian", "Ozias", "Leroy", "Neil", "Watson", "Agustin", 
    "Bryer", "Jerry", "Dillon", "Eren", "Eugene", "Ayan", "Melvin", "Nixon", 
    "Reuben", "Stanley", "Grey", "Loyal", "Alec", "Casper", "Dane", "Azaiah", 
    "Byron", "Joe", "Emory", "Zaylen", "Massimo", "Trenton", "Gatlin", "Joey", 
    "Benny", "Jon", "Jrue", "Gian", "Seven", "Colten", "Ernesto", "Fisher", 
    "Teddy", "Kaisen", "Zechariah", "Darian", "Salvatore", "Jericho", 
    "Mitchell", "Alistair", "Calum", "Van", "Zev", "Langston", "Mccoy", 
    "Ulises", "Lucien", "Benedict", "Carlo", "Coleson", "Meir", "Henrik", 
    "Jiraiya", "Kellan", "Alfonso", "Azai", "Campbell", "Kylen", "Felipe", 
    "Leif", "Rowdy", "Curtis", "Ameer", "Kiaan", "Maurice", "Krue", "Shimon", 
    "Zyon", "Damari", "Jairo", "Khalid", "Kabir", "Jireh", "Mathew", "Shepard", 
    "Eddie", "Isael", "Arden", "Cedric", "Nazir", "Alessio", "Khai", 
    "Marcellus", "Wesson", "Yisroel", "Zymir", "Landyn", "Darren", "Legacy", 
    "Devon", "Judson", "Vihaan", "Yitzchok", "Zen", "Dangelo", "Adler", "Aspen", 
    "Brodie", "Kase", "Khaza", "Mordechai", "Dash", "Makari", "Neo", "Zavier", 
    "Evren", "Imran", "Laith", "Cain", "Ira", "Osiris", "Shlomo", "Yaakov", 
    "Ephraim", "Shmuel", "Wallace", "Yeshua", "Kannon", "Kingsley", "Noa", 
    "TRUE", "Ermias", "Harold", "Joziah", "Rene", "Truce", "Aldo", "Dimitri", 
    "Halo", "Ronnie", "Vance", "Aden", "Ishaan", "Kace", "Stefan"
]

USA_first_names_female = [
    "Olivia", "Emma", "Amelia", "Charlotte", "Mia", "Sophia", "Isabella", 
    "Evelyn", "Ava", "Sofia", "Camila", "Harper", "Luna", "Eleanor", "Violet", 
    "Aurora", "Elizabeth", "Eliana", "Hazel", "Chloe", "Ellie", "Nora", 
    "Gianna", "Lily", "Emily", "Aria", "Scarlett", "Penelope", "Zoe", "Ella", 
    "Avery", "Abigail", "Mila", "Lucy", "Isla", "Ivy", "Layla", "Lainey", 
    "Nova", "Grace", "Willow", "Riley", "Emilia", "Naomi", "Elena", 
    "Madison", "Valentina", "Victoria", "Stella", "Delilah", "Maya", "Hannah", 
    "Leah", "Lillian", "Genesis", "Josephine", "Sadie", "Adeline", "Zoey", 
    "Sophie", "Paisley", "Alice", "Ruby", "Eloise", "Madelyn", "Leilani", 
    "Claire", "Addison", "Ayla", "Emery", "Iris", "Eden", "Natalie", "Maria", 
    "Maeve", "Daisy", "Vivian", "Clara", "Autumn", "Liliana", "Everly", 
    "Audrey", "Lyla", "Jade", "Kinsley", "Millie", "Madeline", "Josie", 
    "Kennedy", "Athena", "Melody", "Caroline", "Aaliyah", "Anna", "Sarah", 
    "Quinn", "Lydia", "Lucia", "Allison", "Hailey", "Ailany", "Cora", 
    "Ariana", "Parker", "Natalia", "Gabriella", "Savannah", "Brooklyn", 
    "Bella", "Georgia", "Juniper", "Alaia", "Raelynn", "Hadley", "Rose", 
    "Julia", "Serenity", "Eliza", "Margaret", "Eva", "Amara", "Melanie", 
    "Cecilia", "Ashley", "Rylee", "Margot", "Samantha", "Catalina", 
    "Juliette", "Aubrey", "Esther", "Mary", "Nevaeh", "Skylar", "Alina", 
    "Amira", "Ember", "Magnolia", "Sienna", "Charlie", "Elliana", "Summer", 
    "Alana", "Brielle", "Remi", "Sage", "Valerie", "Hallie", "Wrenley", 
    "Kehlani", "Emerson", "June", "Sloane", "Emersyn", "Elsie", "Oaklynn", 
    "Oakley", "Blakely", "Freya", "Piper", "Valeria", "Arya", "Adalynn", 
    "Everleigh", "Genevieve", "Anastasia", "Isabel", "Peyton", "Amaya", 
    "Isabelle", "Olive", "Ruth", "Ximena", "Evangeline", "Katherine", 
    "Callie", "Rosalie", "Alani", "Lilah", "Kaia", "Brianna", "Bailey", 
    "Phoebe", "Vivienne", "Andrea", "Myla", "Lia", "Sara", "Kylie", "Reese", 
    "Annie", "Daphne", "Ada", "Adaline", "Arianna", "Ariella", "Sutton", 
    "Celeste", "Jasmine", "Mackenzie", "Haven", "Scottie", "Gemma", "Ana", 
    "Tatum", "Arabella", "Lila", "Molly", "Stevie", "Blake", "Aitana", 
    "Alaina", "Wren", "River", "Noelle", "Delaney", "Journee", "Blair", 
    "Adalyn", "Kaylee", "Alexandra", "Mabel", "Norah", "Presley", "Alora", 
    "Vera", "Celine", "Amy", "Brynlee", "Nyla", "Saylor", "Khloe", 
    "Antonella", "Zara", "Aliyah", "Cataleya", "Lennon", "Kiara", "Camille", 
    "Dahlia", "Kaylani", "Mariana", "Diana", "Reagan", "Selena", "Kimberly", 
    "Rachel", "Gracie", "Faith", "Juliana", "Miriam", "Elise", "Noa", 
    "Elaina", "Maisie", "Lilith", "Collins", "Palmer", "Lilly", "Shiloh", 
    "Ophelia", "Elianna", "Lena", "Harmony", "Aspen", "Rowan", "Gia", "Leila", 
    "Jane", "Talia", "Adelaide", "Dakota", "Lola", "Lucille", "Kailani", 
    "Morgan", "Zuri", "Milani", "Daniela", "Selah", "Alessia", "Angela", 
    "Juliet", "Evie", "Amora", "Rory", "Marley", "Sydney", "Alanna", "Leia", 
    "Luciana", "Kamila", "Harlow", "Kali", "Octavia", "Amari", "Sawyer", 
    "Gabriela", "Ariel", "Maggie", "Rosemary", "Ryleigh", "Tessa", 
    "Evelynn", "Londyn", "Danna", "Amina", "Brooke", "Samara", "Kendall", 
    "Rosie", "Alayna", "Angelina", "Francesca", "Adelyn", "Fatima", "Hope", 
    "Nicole", "Nayeli", "Catherine", "Nina", "Journey", "Adriana", "Camilla", 
    "Ailani", "Malia", "Meadow", "Jordyn", "Joanna", "Emory", "Malani", 
    "Serena", "Teagan", "Aurelia", "Vanessa", "Kayla", "Navy", "Poppy", 
    "Kalani", "Regina", "Adelina", "Rebecca", "Ariyah", "Esme", "Heidi", 
    "Aisha", "Julieta", "Thea", "Annabelle", "Esmeralda", "Lauren", 
    "Julianna", "Taylor", "Wrenlee", "London", "Giselle", "Sabrina", 
    "Azalea", "Laura", "Sylvie", "Sylvia", "Alaya", "Raya", "Elora", 
    "Finley", "Mya", "Dream", "Viviana", "Elaine", "Elodie", "Laila", 
    "Sunny", "Briella", "Lana", "Paige", "Itzel", "Mckenna", "Melissa", 
    "Frances", "Mira", "Payton", "Hattie", "Astrid", "Brynn", "Winter", 
    "Aylin", "Miley", "Raven", "Jocelyn", "Maryam", "Logan", "Veronica", 
    "Gwendolyn", "Anya", "Leighton", "Alivia", "Harley", "Charlee", "Alyssa", 
    "Colette", "Hayden", "Lorelai", "Jayla", "Ivory", "Anaya", "Fiona", 
    "Trinity", "Aubree", "Michelle", "Matilda", "Lilliana", "Mallory", 
    "Mariah", "Helena", "Wynter", "Carmen", "Alayah", "Liana", "Holly", 
    "Madilyn", "Phoenix", "Raelyn", "Willa", "Helen", "Emely", "Alessandra", 
    "Gracelynn", "Carolina", "Arleth", "Salem", "Dorothy", "Xiomara", 
    "Elisa", "Reign", "Florence", "Alicia", "Madeleine", "Melany", 
    "Katalina", "Zariah", "Bonnie", "Joy", "Kaliyah", "Haisley", "Sarai", 
    "Blaire", "Elowyn", "Saige", "Adelynn", "Opal", "Demi", "Nylah", "Emmy", 
    "Camryn", "Kira", "Lorelei", "Daleyza", "Raegan", "Maia", "Bianca", 
    "Aniyah", "Annalise", "Alexandria", "Amirah", "Alison", "Anahi", 
    "Gracelyn", "Brooklynn", "Miracle", "Everlee", "Adhara", "Alma", "Macie", 
    "Murphy", "Romina", "Cassidy", "Clementine", "Heaven", "Elle", "Skye", 
    "Destiny", "Lyra", "Rylie", "Paris", "Cameron", "Felicity", "Maddison", 
    "Leona", "Scarlet", "Kora", "Mariam", "Meredith", "Mckenzie", "Dayana", 
    "Cali", "Amanda", "Arielle", "Angel", "Calliope", "Fernanda", "Estella", 
    "April", "Izabella", "Hanna", "Marceline", "Alexis", "Carter", 
    "Daniella", "Marlee", "Virginia", "Kataleya", "Halo", "Nadia", "Amiyah", 
    "Madelynn", "Emerie", "Renata", "Oaklee", "Remington", "Maxine", 
    "Nellie", "Briar", "Danielle", "Charli", "Makenna", "Imani", "Armani", 
    "Edith", "Nalani", "Mae", "Vienna", "Hadassah", "Stephanie", "Ari", 
    "Kate", "Jimena", "Briana", "Faye", "Jordan", "Louise", "Amber", 
    "Makayla", "Zahra", "Lylah", "Margo", "Amoura", "Jennifer", "Kyla", 
    "Mylah", "Winnie", "Alisson", "Amalia", "Reina", "Avianna", "Allie", 
    "Ivanna", "Ariya", "Lilian", "Alia", "Aylani", "Noah", "Reyna", "Lexi", 
    "Brinley", "Iyla", "Mavis", "Lina", "Cecelia", "Eve", "Maren", "Monroe", 
    "Capri", "Emelia", "Jessica", "Halle", "Alejandra", "Gabrielle", "Yara", 
    "Beatrice", "Della", "Kamryn", "Katie", "Ariah", "Arlette", "Noemi", 
    "Alondra", "Maliyah", "Mara", "Jacqueline", "Jazlyn", "Frankie", "Angie", 
    "Eileen", "Lyric", "Aliana", "Sierra", "Rosalia", "Oaklyn", "Chaya", 
    "Amaia", "Leyla", "Holland", "Cleo", "Jream", "Leslie", "Sevyn", 
    "Jolene", "Mina", "Keira", "Legacy", "Tiana", "Elliott", "Cassandra", 
    "Jaylani", "Priscilla", "Rhea", "Kinley", "Clover", "Estrella", 
    "Zariyah", "Journi", "Miranda", "Angelica", "Marlowe", "Jovie", "Abby", 
    "Sariyah", "Kenzie", "Oakleigh", "Aya", "Siena", "Emberly", "Melina", 
    "Amani", "Bristol", "Estelle", "Galilea", "Irene", "Marie", "Marina", 
    "Makenzie", "Sasha", "Paislee", "Isabela", "Goldie", "Myra", "Davina", 
    "Flora", "Anne", "Azariah", "Indie", "Kaitlyn", "Jazmin", "Gloria", 
    "Georgina", "Shelby", "Dallas", "Thalia", "Aliza", "Averie", "Skyler", 
    "Macy", "Rosa", "Dulce", "Khaleesi", "Marilyn", "Martha", "Adley", 
    "Belen", "Ellianna", "Kelsey", "Nia", "Chana", "Lakelynn", "Selene", 
    "Lottie", "Loretta", "Aleena", "Ila", "Dani", "Remy", "Whitley", 
    "Jenna", "Lillie", "Kennedi", "Violeta", "Kendra", "Lennox", "Laney", 
    "Aviana", "Solana", "Veda", "Marigold", "Billie", "Drew", "Dylan", 
    "Ellis", "Gwen", "Amayah", "Milan", "Leilany", "Ryan", "Bridget", 
    "Christina", "Ezra", "Ainsley", "Emerald", "Hana", "Noor", "Rivka", 
    "Amelie", "Jenesis", "Royalty", "Lenora", "Taytum", "Jamie", "Kathryn", 
    "Aileen", "Arlet", "Coraline", "Kiana", "Kyra", "Araceli", "Azaria", 
    "Kenna", "Monica", "Bethany", "Laurel", "Charley", "Karla", "Kayleigh", 
    "Rayna", "Louisa", "Celia", "Emmie", "Fallon", "Persephone", "Winona", 
    "Marisol", "Lara", "Kensley", "Mckinley", "Michaela", "Novalee", 
    "Elyse", "Lacey", "Penny", "Zelda", "Alena", "Luz", "Keilani", "Nala", 
    "Paula", "Birdie", "Karsyn", "Lakelyn", "Miller", "Jemma", "Aleah", 
    "Inaya", "Megan", "Sloan", "Charleigh", "Rosalina", "Andi", "Nola", 
    "Julie", "Adrianna", "Kaeli", "Addilyn", "Freyja", "Ramona", "Samira", 
    "Karina", "Denver", "Janelle", "Mikayla", "Seraphina", "Haley", "Indy", 
    "Paulina", "Rowyn", "Milana", "Chelsea", "Elina", "Milena", "Valery", 
    "Ivey", "Maci", "Stormi", "Brittany", "Madilynn", "Aila", "Yareli", 
    "Yaretzi", "Zaylee", "Erin", "Adele", "Robin", "Jaliyah", "Maisy", 
    "Pearl", "Adalee", "Brynleigh", "Keyla", "Alexa", "Baylor", "Jessie", 
    "Cielo", "Braelynn", "Alianna", "Theodora", "Malaya", "Meilani", 
    "Tallulah", "Analia", "Nyomi", "Promise", "Sol", "Xyla", "Kylee", 
    "Marjorie", "Treasure", "Soleil", "Zaria", "Cynthia", "Luella", "Sky", 
    "Ayleen", "Neriah", "Iliana", "Judith", "Ocean", "Lea", "Linda", "Livia", 
    "Maddie", "Magdalena", "Elia", "Kahlani", "Micah", "Tiffany", 
    "Wrenleigh", "Zaniyah", "Kallie", "Love", "Andie", "Johanna", "Mercy", 
    "Skyla", "Aliya", "Deborah", "Zainab", "Anais", "Greta", "Kaiya", 
    "Malaysia", "Marianna", "Amaris", "Barbara", "Bellamy", "Dalia", "Anika", 
    "Giana", "Keziah", "Nataly", "Cheyenne", "Kelly", "Luisa", "Salma", 
    "Teresa", "Aura", "Carly", "Liv", "Azari", "Dafne", "Rebekah", "Amiri", 
    "Berkley", "Emberlynn", "Hunter", "Jaycee", "Alexia", "Reya", "Ruthie", 
    "Eleanora", "Janiyah", "Rosalyn", "Giuliana", "Emiliana", "Novah", "Tru", 
    "Kori", "Aspyn", "Chandler", "Kailany", "Lilyana", "Elowen", "Khalani", 
    "Naya", "Zyla", "Jolie", "Leanna", "Yamileth", "Cattleya", "Elisabeth", 
    "Ensley", "Ashlyn", "Allyson", "August", "Kimber", "Marleigh", "Soraya", 
    "Anaiah", "Analeia", "Waverly", "Yasmin", "Zora", "Joelle", "Lilia", 
    "Nancy", "Icelynn", "Indigo", "Arely", "Laylani", "Romy", "Scout", 
    "Ayra", "Giovanna", "Siya", "Katelyn", "Madalyn", "Natasha", "Alaiya", 
    "Honey", "Lettie", "Sarahi", "Elsa", "Emmeline", "Hadlee", "Lilianna", 
    "Zendaya", "Ainhoa", "Elliot", "Jazmine", "Aadhya", "Guinevere", "Rayne", 
    "Clare", "Saanvi", "Campbell", "Salome", "Tilly", "Yusra", "Akira", 
    "Henley", "Lyanna", "Quincy", "Rosalee", "Vada", "Ainara", "Annika", 
    "Ayah", "Violette", "Aleia", "Kaya", "Mazie", "Amyra", "Celina", 
    "Mikaela", "Paloma", "Elouise", "Etta", "Julietta", "Kamiyah", "Zoya", 
    "Jayleen", "Kassidy", "Keily", "Harlee", "Kiera", "Liberty", "Darcy", 
    "Dior", "Lisa", "Malka", "Arisbeth", "Kara", "Bailee", "Elani", 
    "Harmoni", "Mariella", "Zayla", "Emi", "Jianna", "Maelynn", "Avani", 
    "Lavender", "Karter", "Raina"
]

USA_last_names = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", 
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", 
    "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", 
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", 
    "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King", 
    "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", 
    "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", 
    "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", 
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", 
    "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", 
    "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", 
    "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks", "Chavez", 
    "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes", 
    "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", 
    "Ross", "Foster", "Jimenez", "Powell", "Jenkins", "Perry", "Russell", 
    "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes", 
    "Gonzales", "Fisher", "Vasquez", "Simmons", "Romero", "Jordan", 
    "Patterson", "Alexander", "Hamilton", "Graham", "Reynolds", "Griffin", 
    "Wallace", "Moreno", "West", "Cole", "Hayes", "Bryant", "Herrera", 
    "Gibson", "Ellis", "Tran", "Medina", "Aguilar", "Stevens", "Murray", 
    "Ford", "Castro", "Marshall", "Owens", "Harrison", "Fernandez", 
    "Mcdonald", "Woods", "Washington", "Kennedy", "Wells", "Vargas", 
    "Henry", "Chen", "Freeman", "Webb", "Tucker", "Guzman", "Burns", 
    "Crawford", "Olson", "Simpson", "Porter", "Hunter", "Gordon", "Mendez", 
    "Silva", "Shaw", "Snyder", "Mason", "Dixon", "Munoz", "Hunt", "Hicks", 
    "Holmes", "Palmer", "Wagner", "Black", "Robertson", "Boyd", "Rose", 
    "Stone", "Salazar", "Fox", "Warren", "Mills", "Meyer", "Rice", 
    "Schmidt", "Garza", "Daniels", "Ferguson", "Nichols", "Stephens", 
    "Soto", "Weaver", "Ryan", "Gardner", "Payne", "Grant", "Dunn", "Kelley", 
    "Spencer", "Hawkins", "Arnold", "Pierce", "Vazquez", "Hansen", "Peters", 
    "Santos", "Hart", "Bradley", "Knight", "Elliott", "Cunningham", 
    "Duncan", "Armstrong", "Hudson", "Carroll", "Lane", "Riley", "Andrews", 
    "Alvarado", "Ray", "Delgado", "Berry", "Perkins", "Hoffman", "Johnston", 
    "Matthews", "Pena", "Richards", "Contreras", "Willis", "Carpenter", 
    "Lawrence", "Sandoval", "Guerrero", "George", "Chapman", "Rios", 
    "Estrada", "Ortega", "Watkins", "Greene", "Nunez", "Wheeler", "Valdez", 
    "Harper", "Burke", "Larson", "Santiago", "Maldonado", "Morrison", 
    "Franklin", "Carlson", "Austin", "Dominguez", "Carr", "Lawson", 
    "Jacobs", "Obrien", "Lynch", "Singh", "Vega", "Bishop", "Montgomery", 
    "Oliver", "Jensen", "Harvey", "Williamson", "Gilbert", "Dean", "Sims", 
    "Espinoza", "Howell", "Li", "Wong", "Reid", "Hanson", "Le", "Mccoy", 
    "Garrett", "Burton", "Fuller", "Wang", "Weber", "Welch", "Rojas", 
    "Lucas", "Marquez", "Fields", "Park", "Yang", "Little", "Banks", 
    "Padilla", "Day", "Walsh", "Bowman", "Schultz", "Luna", "Fowler", 
    "Mejia", "Davidson", "Acosta", "Brewer", "May", "Holland", "Juarez", 
    "Newman", "Pearson", "Curtis", "Cortez", "Douglas", "Schneider", 
    "Joseph", "Barrett", "Navarro", "Figueroa", "Keller", "Avila", "Wade", 
    "Molina", "Stanley", "Hopkins", "Campos", "Barnett", "Bates", "Chambers", 
    "Caldwell", "Beck", "Lambert", "Miranda", "Byrd", "Craig", "Ayala", 
    "Lowe", "Frazier", "Powers", "Neal", "Leonard", "Gregory", "Carrillo", 
    "Sutton", "Fleming", "Rhodes", "Shelton", "Schwartz", "Norris", 
    "Jennings", "Watts", "Duran", "Walters", "Cohen", "Mcdaniel", "Moran", 
    "Parks", "Steele", "Vaughn", "Becker", "Holt", "Deleon", "Barker", 
    "Terry", "Hale", "Leon", "Hail", "Benson", "Haynes", "Horton", "Miles", 
    "Lyons", "Pham", "Graves", "Bush", "Thornton", "Wolfe", "Warner", 
    "Cabrera", "Mckinney", "Mann", "Zimmerman", "Dawson", "Lara", "Fletcher", 
    "Page", "Mccarthy", "Love", "Robles", "Cervantes", "Solis", "Erickson", 
    "Reeves", "Chang", "Klein", "Salinas", "Fuentes", "Baldwin", "Daniel", 
    "Simon", "Velasquez", "Hardy", "Higgins", "Aguirre", "Lin", "Cummings", 
    "Chandler", "Sharp", "Barber", "Bowen", "Ochoa", "Dennis", "Robbins", 
    "Liu", "Ramsey", "Francis", "Griffith", "Paul", "Blair", "Oconnor", 
    "Cardenas", "Pacheco", "Cross", "Calderon", "Quinn", "Moss", "Swanson", 
    "Chan", "Rivas", "Khan", "Rodgers", "Serrano", "Fitzgerald", "Rosales", 
    "Stevenson", "Christensen", "Manning", "Gill", "Curry", "Mclaughlin", 
    "Harmon", "Mcgee", "Gross", "Doyle", "Garner", "Newton", "Burgess", 
    "Reese", "Walton", "Blake", "Trujillo", "Adkins", "Brady", "Goodman", 
    "Roman", "Webster", "Goodwin", "Fischer", "Huang", "Potter", "Delacruz", 
    "Montoya", "Todd", "Wu", "Hines", "Mullins", "Castaneda", "Malone", 
    "Cannon", "Tate", "Mack", "Sherman", "Hubbard", "Hodges", "Zhang", 
    "Guerra", "Wolf", "Valencia", "Franco", "Saunders", "Rowe", "Gallagher", 
    "Farmer", "Hammond", "Hampton", "Townsend", "Ingram", "Wise", 
    "Gallegos", "Clarke", "Barton", "Schroeder", "Maxwell", "Waters", 
    "Logan", "Camacho", "Strickland", "Norman", "Person", "Colon", 
    "Parsons", "Frank", "Harrington", "Glover", "Osborne", "Buchanan", 
    "Casey", "Floyd", "Patton", "Ibarra", "Ball", "Tyler", "Suarez", 
    "Bowers", "Orozco", "Salas", "Cobb", "Gibbs", "Andrade", "Bauer", 
    "Conner", "Moody", "Escobar", "Mcguire", "Lloyd", "Mueller", "Hartman", 
    "French", "Kramer", "Mcbride", "Pope", "Lindsey", "Velazquez", "Norton", 
    "Mccormick", "Sparks", "Flynn", "Yates", "Hogan", "Marsh", "Macias", 
    "Villanueva", "Zamora", "Pratt", "Stokes", "Owen", "Ballard", "Lang", 
    "Brock", "Villarreal", "Charles", "Drake", "Barrera", "Cain", "Patrick", 
    "Pineda", "Burnett", "Mercado", "Santana", "Shepherd", "Bautista", 
    "Ali", "Shaffer", "Lamb", "Trevino", "Mckenzie", "Hess", "Beil", 
    "Olsen", "Cochran", "Morton", "Nash", "Wilkins", "Petersen", "Briggs", 
    "Shah", "Roth", "Nicholson", "Holloway", "Lozano", "Flowers", "Rangel", 
    "Hoover", "Arias", "Short", "Mora", "Valenzuela", "Bryan", "Meyers", 
    "Weiss", "Underwood", "Bass", "Greer", "Summers", "Houston", "Carson", 
    "Morrow", "Clayton", "Whitaker", "Decker", "Yoder", "Collier", "Zuniga", 
    "Carey", "Wilcox", "Melendez", "Poole", "Roberson", "Larsen", "Conley", 
    "Davenport", "Copeland", "Massey", "Lam", "Huff", "Rocha", "Cameron", 
    "Jefferson", "Hood", "Monroe", "Anthony", "Pittman", "Huynh", 
    "Randall", "Singleton", "Kirk", "Combs", "Mathis", "Christian", 
    "Skinner", "Bradford", "Richard", "Galvan", "Wall", "Boone", "Kirby", 
    "Wilkinson", "Bridges", "Bruce", "Atkinson", "Velez", "Meza", "Roy", 
    "Vincent", "York", "Hodge", "Villa", "Abbott", "Allison", "Tapia", 
    "Gates", "Chase", "Sosa", "Sweeney", "Farrell", "Wyatt", "Dalton", 
    "Horn", "Barron", "Phelps", "Yu", "Dickerson", "Heath", "Foley", 
    "Atkins", "Mathews", "Bonilla", "Acevedo", "Benitez", "Zavala", 
    "Hensley", "Glenn", "Cisneros", "Harrell", "Shields", "Rubio", "Choi", 
    "Huffman", "Boyer", "Garrison", "Arroyo", "Bond", "Kane", "Hancock", 
    "Callahan", "Dillon", "Cline", "Wiggins", "Grimes", "Arellano", 
    "Melton", "Oneill", "Savage", "Ho", "Beltran", "Pitts", "Parrish", 
    "Ponce", "Rich", "Booth", "Koch", "Golden", "Ware", "Brennan", 
    "Mcdowell", "Marks", "Cantu", "Humphrey", "Baxter", "Sawyer", "Clay", 
    "Tanner", "Hutchinson", "Kaur", "Berg", "Wiley", "Gilmore", "Russo", 
    "Villegas", "Hobbs", "Keith", "Wilkerson", "Ahmed", "Beard", "Mcclain", 
    "Montes", "Mata", "Rosario", "Vang", "S", "Walter", "Henson", 
    "Oneal", "Mosley", "Mcclure", "Beasley", "Stephenson", "Snow", "Huerta", 
    "Preston", "Vance", "Barry", "Johns", "Eaton", "Blackwell", "Dyer", 
    "Prince", "Macdonald", "Solomon", "Guevara", "Stafford", "English", 
    "Hurst", "Woodard", "Cortes", "Shannon", "Kemp", "Nolan", "Mccullough", 
    "Merritt", "Murillo", "Moon", "Salgado", "Strong", "Kline", "Cordova", 
    "Barajas", "Roach", "Rosas", "Winters", "Jacobson", "Lester", "Knox", 
    "Bullock", "Kerr", "Leach", "Meadows", "Davila", "Orr", "Whitehead", 
    "Pruitt", "Kent", "Conway", "Mckee", "Barr", "David", "Dejesus", 
    "Marin", "Berger", "Mcintyre", "Blankenship", "Gaines", "Palacios", 
    "Cuevas", "Bartlett", "Durham", "Dorsey", "Mccall", "Odonnell", 
    "Stein", "Browning", "Stout", "Lowery", "Sloan", "Mclean", "Hendricks", 
    "Calhoun", "Sexton", "Chung", "Gentry", "Hull", "Duarte", "Ellison", 
    "Nielsen", "Gillespie", "Buck", "Middleton", "Sellers", "Leblanc", 
    "Esparza", "Hardin", "Bradshaw", "Mcintosh", "Howe", "Livingston", 
    "Frost", "Glass", "Morse", "Knapp", "Herman", "Stark", "Bravo", 
    "Noble", "Spears", "Weeks", "Corona", "Frederick", "Buckley", 
    "Mcfarland", "Hebert", "Enriquez", "Hickman", "Quintero", "Randolph", 
    "Schaefer", "Walls", "Trejo", "House", "Reilly", "Pennington", 
    "Michael", "Conrad", "Giles", "Benjamin", "Crosby", "Fitzpatrick", 
    "Donovan", "Mays", "Mahoney", "Valentine", "Raymond", "Medrano", 
    "Hahn", "Mcmillan", "Small", "Bentley", "Felix", "Peck", "Lucero", 
    "Boyle", "Hanna", "Pace", "Rush", "Hurley", "Harding", "Mcconnell", 
    "Bernal", "Nava", "Ayers", "Everett", "Ventura", "Avery", "Pugh", 
    "Mayer", "Bender", "Shepard", "Mcmahon", "Landry", "Case", "Sampson", 
    "Moses", "Magana", "Blackburn", "Dunlap", "Gould", "Duffy", "Vaughan", 
    "Herring", "Mckay", "Espinosa", "Rivers", "Farley", "Bernard", 
    "Ashley", "Friedman", "Potts", "Truong", "Costa", "Correa", "Blevins", 
    "Nixon", "Clements", "Fry", "Delarosa", "Best", "Benton", "Lugo", 
    "Portillo", "Dougherty", "Crane", "Haley", "Phan", "Villalobos", 
    "Blanchard", "Horne", "Finley", "Quintana", "Lynn", "Esquivel", 
    "Bean", "Dodson", "Mullen", "Xiong", "Hayden", "Cano", "Levy", 
    "Huber", "Richmond", "Moyer", "Lim", "Frye", "Sheppard", "Mccarty", 
    "Avalos", "Booker", "Waller", "Parra", "Woodward", "Jaramillo", 
    "Krueger", "Rasmussen", "Brandt", "Peralta", "Donaldson", "Stuart", 
    "Faulkner", "Maynard", "Galindo", "Coffey", "Estes", "Sanford", 
    "Burch", "Maddox", "Vo", "Oconnell", "Vu", "Andersen", 
    "Spence", "Mcpherson", "Church", "Schmitt", "Stanton", "Leal", 
    "Cherry", "Compton", "Dudley", "Sierra", "Pollard", "Alfaro", "Hester", 
    "Proctor", "Lu", "Hinton", "Novak", "Good", "Madden", "Mccann", 
    "Terrell", "Jarvis", "Dickson", "Reyna", "Cantrell", "Mayo", "Branch", 
    "Hendrix", "Rollins", "Rowland", "Whitney", "Duke", "Odom", 
    "Daugherty", "Travis", "Tang"
]

zodiac_sign = ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 
    'Capricorn', 'Aquarius', 'Pisces']

religions = ['Christianity', 'Islam', 'Hinduism', 'Buddhism', 'Judaism', 'Sikhism', 'Bahá\'í Faith', 'Shinto',
    'Confucianism', 'Jainism', 'Taoism', 'Zoroastrianism', 'Paganism', 'Unitarian Universalism', 'Wicca']

colors = [
    'Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Pink', 'Brown',
    'Black', 'White', 'Gray', 'Silver', 'Gold',
    'Crimson', 'Scarlet', 'Ruby', 'Cherry', 'Rose', 'Coral', 'Salmon',
    'Tomato', 'Maroon', 'Burgundy', 'Wine', 'Mahogany', 'Rust', 'Vermilion',
    'Navy', 'Royalblue', 'Azure', 'Cerulean', 'Cobalt', 'Sapphire',
    'Indigo', 'Skyblue', 'Turquoise', 'Qqua', 'Qquamarine', 'Teal',
    'Powderblue', 'Midnightblue', 'Steelblue', 'Slateblue',
    'Lime', 'Emerald', 'Jade', 'Mint', 'Forestgreen', 'Olive',
    'Seagreen', 'Limegreen', 'Chartreuse', 'Kellygreen', 'Shamrock',
    'Gold', 'Amber', 'Lemon', 'Mustard', 'Saffron', 'Sunflower',
    'Tangerine', 'Peach', 'Apricot', 'Pumpkin', 'Carrot', 'Ginger',
    'Violet', 'Lavender', 'Mauve', 'Magenta', 'Fuchsia', 'Plum',
    'Orchid', 'Lilac', 'Periwinkle', 'Amethyst', 'Eggplant',
    'Hotpink', 'Blush', 'Carnation', 'Flamingo', 'Raspberry',
    'Strawberry', 'Bubblegum', 'Cottoncandy',
    'Chocolate', 'Cocoa', 'Coffee', 'Tan', 'Beige', 'Khaki', 'Taupe',
    'Camel', 'Sand', 'Sienna', 'Cinnamon', 'Bronze', 'Copper', 'Sepia',
    'Charcoal', 'Ash', 'Slate', 'Ivory', 'Cream', 'Linen',
    'Cyan', 'Peacock', 'Watermelon', 'Terracotta', 'Ochre', 'Paprika'
]

animals = [
    "Dog", "Cat", "Elephant", "Lion", "Tiger", "Bear", "Wolf", "Fox",
    "Deer", "Rabbit", "Squirrel", "Mouse", "Rat", "Horse", "Cow", "Pig",
    "Sheep", "Goat", "Monkey", "Gorilla", "Chimpanzee", "Kangaroo", "Koala",
    "Panda", "Whale", "Dolphin", "Seal", "Walrus", "Bat",
    "Hippopotamus", "Rhinoceros", "Giraffe", "Zebra", "Cheetah", "Leopard",
    "Sloth", "Armadillo", "Anteater", "Lemur", "Platypus", "Echidna",
    "Eagle", "Hawk", "Owl", "Parrot", "Robin", "Sparrow", "Penguin",
    "Ostrich", "Emu", "Pelican", "Flamingo", "Swan", "Duck", "Goose",
    "Chicken", "Turkey", "Peacock", "Dove", "Crow", "Raven",
    "Salmon", "Tuna", "Shark", "Goldfish", "Clownfish", "Eel", "Trout",
    "Bass", "Pike", "Mackerel", "Cod", "Herring", "Sardine", "Anchovy",
    "Snake", "Lizard", "Turtle", "Tortoise", "Crocodile", "Alligator",
    "Iguana", "Gecko", "Chameleon", "Python", "Cobra", "Rattlesnake",
    "Frog", "Toad", "Salamander", "Newt", "Axolotl",
    "Ant", "Bee", "Butterfly", "Moth", "Fly", "Mosquito", "Dragonfly",
    "Grasshopper", "Cricket", "Spider", "Scorpion", "Centipede", "Millipede",
    "Beetle", "Ladybug", "Firefly", "Wasp", "Hornet", "Termite",
    "Octopus", "Squid", "Jellyfish", "Starfish", "Sea Urchin",
    "Crab", "Lobster", "Shrimp", "Seahorse", "Ray"
]

seasons = ['Spring', 'Summer', 'Fall', 'Winter']

foods = [
    "Pizza", "Pasta", "Lasagna", "Spaghetti", "Ravioli", "Risotto", "Gelato",
    "Hamburger", "Cheeseburger", "Hot Dog", "Fried Chicken", "Steak",
    "Mac and Cheese", "BBQ Ribs", "Apple Pie", "Chocolate Chip Cookies",
    "Grilled Cheese", "Cornbread", "Fried Fish",
    "Sushi", "Ramen", "Fried Rice", "Chow Mein", "Pad Thai", "Kimchi",
    "Bulgogi", "Curry", "Dumplings", "Spring Rolls", "Dim Sum",
    "Tacos", "Burrito", "Quesadilla", "Enchilada", "Tamale",
    "Nachos", "Guacamole", "Salsa",
    "Pancakes", "Waffles", "French Toast", "Scrambled Eggs", "Bacon",
    "Sausage", "Oatmeal", "Yogurt", "Granola", "Bagel", "Croissant", "Scone",
    "Chocolate", "Ice Cream", "Cake", "Brownie", "Cookie", "Popcorn",
    "Potato Chips", "Peanuts", "Almonds",
    "Falafel", "Hummus", "Shawarma", "Kebab", "Paella", "Crepe",
    "Salmon", "Tuna", "Shrimp", "Lobster", "Crab", "Scallops",
    "Salad", "Quinoa Bowl", "Avocado Toast", "Veggie Burger",
    "Mashed Potatoes", "French Fries", "Chicken Soup", "Bread", "Cheese"
]

USA_political_side = [
    "Democratic Party", "Republican Party", "Libertarian Party", "Green Party",
    "Constitution Party", "Working Families Party", "Socialist Party USA", "Peace and Freedom Party",
    "Reform Party", "Liberal", "Conservative", "Moderate",
    "Progressive", "Libertarian", "Socialist", "Populist", "Centrist",
    "Democratic Socialist", "Neoliberal", "Neoconservative", "Classical Liberal",
    "Social Liberal", "Fiscal Conservative", "Social Conservative", "Paleoconservative",
    "Left-Wing", "Right-Wing", "Center-Left", "Center-Right",
    "Far-Left", "Far-Right", "Establishment", "Anti-Establishment",
    "Tea Party Movement", "Democratic Socialists of America (DSA)", "MAGA Republicans", "Never Trump Republicans",
    "Blue Dog Democrats", "Progressive Caucus"
]

email_providers = [
    'gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com',
    'live.com', 'icloud.com', 'me.com', 'mac.com', 'protonmail.com',
    'tutanota.com', 'tutanota.de', 'mailfence.com', 'hushmail.com', 'fastmail.com', 'zoho.com',
    'gmx.com', 'gmx.de', 'mail.com', 'inbox.com', 'yandex.com', 'mail.ru', 'aol.com',
    'comcast.net', 'sbcglobal.net', 'att.net', 'cox.net', 'earthlink.net', 'rediffmail.com',
    'seznam.cz', 'yahoo.co.uk', 'rocketmail.com'
]

eyes_color = [
    "Brown", "Amber", "Hazel", "Green", "Blue", "Gray"
]

hairs_color = [
    "Black", "Brown", "Auburn", "Red", "Blonde", "Gray", "White"
]

USA_cities = [
    "New York", "Los Angeles", "Chicago", "Houston", "Phoenix",
    "Philadelphia", "San Antonio", "San Diego", "Dallas", "San Jose",
    "Austin", "Jacksonville", "Fort Worth", "Columbus", "Indianapolis",
    "Charlotte", "San Francisco", "Seattle", "Denver", "Washington",
    "Nashville", "Oklahoma City", "El Paso", "Boston", "Portland",
    "Las Vegas", "Detroit", "Louisville", "Memphis", "Baltimore",
    "Milwaukee", "Albuquerque", "Tucson", "Fresno", "Mesa",
    "Sacramento", "Atlanta", "Kansas City", "Colorado Springs", "Raleigh",
    "Miami", "Omaha", "Long Beach", "Virginia Beach", "Oakland",
    "Minneapolis", "Tampa", "Tulsa", "Arlington", "New Orleans",
    "Wichita", "Bakersfield", "Cleveland", "Aurora", "Anaheim",
    "Honolulu", "Santa Ana", "Riverside", "Corpus Christi", "Lexington",
    "Stockton", "Henderson", "St. Paul", "Cincinnati", "Pittsburgh",
    "Greensboro", "Anchorage", "Plano", "Lincoln", "Orlando",
    "Irvine", "Newark", "Durham", "Chula Vista", "Toledo",
    "Fort Wayne", "St. Petersburg", "Laredo", "Jersey City", "Madison",
    "Chandler", "Lubbock", "Scottsdale", "Reno", "Buffalo",
    "Gilbert", "Glendale", "North Las Vegas", "Winston-Salem", "Chesapeake",
    "Norfolk", "Fremont", "Garland", "Irving", "Hialeah"
]

blood_types = [
    "A+", "A-", "B+", "B-",
    "AB+", "AB-", "O+", "O-"
]

USA_states = [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
    "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming"
]

def generate_random_birthday():
    today = datetime.today()
    age_range_start = 18
    age_range_end = 50
    age = random.randint(age_range_start, age_range_end)
    birth_year = today.year - age
    random_month = random.randint(1, 12)
    days_in_month = [31, 29 if (birth_year % 4 == 0 and (birth_year % 100 != 0 or birth_year % 400 == 0)) else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    random_day = random.randint(1, days_in_month[random_month - 1])
    random_birthday = datetime(birth_year, random_month, random_day)
    return random_birthday, age
birthday, age = generate_random_birthday()


def get_random_item(item_list):
    return random.choice(item_list)

def get_two_random_item(item2_list, item3_list):
    chosen_list = random.choice([item2_list, item3_list])
    return random.choice(chosen_list)

def id_issued():
    this_year = datetime.now().year
    start_year = this_year - 4
    end_year = this_year
    issued_year = random.randint(start_year, end_year)
    issued_month_id = random.randint(1, 12)
    days_in_month = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    if issued_month_id == 2 and (issued_year % 4 == 0 and (issued_year % 100 != 0 or issued_year % 400 == 0)):
        days_in_feb = 29
    else:
        days_in_feb = 28
    days_in_month[1] = days_in_feb
    issued_day = random.randint(1, days_in_month[issued_month_id - 1])
    return issued_year, issued_month_id, issued_day
year_id, month_id, day_id = id_issued()

def generate_random_person():
    USA_first_name = get_two_random_item(USA_first_names_male, USA_first_names_female)
    if USA_first_name in USA_first_names_male:
        gender = 'M'
    else:
        gender = 'F'
    USA_last_name = get_random_item(USA_last_names)
    return {
        print("IDENTIFICATION CARD".center(80, '-')),
        print(""),
        print("%-3s %-50s" % ("4d", f"LIC No. {random.randint(1000,9990)}-{random.randint(1000,9999)}-{random.randint(100,999)}{random.choice(string.ascii_letters)}")),
        print("%-3s %-50s" % ("3", f"DoB: {birthday.strftime('%B %d, %Y')} (Age: {age})")),
        print("%-3s %-50s %-4s %-120s" % ("4b", f"EXP: {month_id}-{day_id}-{year_id + 5}", "4a", f"ISS: {month_id}-{day_id}-{year_id}")),
        print("%-3s %-50s" % ("1", f"Name: {USA_first_name}")),
        print("%-3s %-50s" % ("2", f"Surname: {USA_last_name}")),
        print("%-3s %-50s" % ("8", f"Address: still need to be programmed")),
        print("%-3s %-50s" % (" ", "City, State, ZIP Code")),
        print(f" "),
        print("%-3s %-50s %-4s %-120s" % ("15", f"SEX: {gender}", "16", f'HGT: {random.randint(4, 6)}"-{random.randint(1, 10)}"')),
        print("%-3s %-50s %-4s %-120s" % ("17", f"WGT: {random.randint(132, 197)} lbs", "18", f"EYES: {get_random_item(eyes_color)}")),
        print(" "),
        print(" "),
        print("MORE ABOUT YOU:".center(80, '-')),
        print("%-3s %-50s %-4s %-120s" % ("3b", f"Birthplace: {get_random_item(USA_cities)}, USA", "3c", f"Zodiac Sign: {get_random_item(zodiac_sign)}")),
        print("%-3s %-50s %-4s %-120s" % ("3d", f"Hair color: {get_random_item(hairs_color)}", "3e", f"Shoe size: {random.randint(5, 20)}")),
        print("%-3s %-50s %-4s %-120s" % ("3f", f"Blood type: {get_random_item(blood_types)}", "3g", f"Religion: {get_random_item(religions)}")),
        print("%-3s %-50s %-4s %-120s" % ("20", f"E-mail: {USA_first_name.lower()}{USA_last_name.lower()}@{get_random_item(email_providers)}", "20a", f"Phone: ({random.randint(100,999)})-{random.randint(200,999)}-{random.randint(1000,9999)}")),
        print("%-3s %-50s %-4s %-120s" % ("21a", f"Political side: {get_random_item(USA_political_side)}", "21b", f"Favorite food: {get_random_item(foods)}")),
        print("%-3s %-50s %-4s %-120s" % ("21c", f"Favorite color: {get_random_item(colors)}", "21d", f"Favorite season: {get_random_item(seasons)}")), 
        print("%-3s %-50s %-4s %-120s" % ("21e", f"Favorite animal: {get_random_item(animals)}", "21f", f"Favorite number: {random.randint(0, 99)}")),
        print(f"Social Security Number (SSN): {random.randint(100, 999)}-{random.randint(10, 99)}-{random.randint(1000,9999)}"),
    }

person = generate_random_person()
print(person)
