import random
from datetime import datetime, timedelta
import string

#================================USA========================================#
##==========================PERSONAL INFORMATION======================##
first_names_male = [
    "Liam", "Noah", "Oliver", "Theodore", "James", "Henry", "Mateo", "Elijah", 
    "Lucas", "William", "Benjamin", "Levi", "Ezra", "Sebastian", "Jack", 
    "Daniel", "Samuel", "Michael", "Ethan", "Asher", "John", "Hudson", "Luca", 
    "Leo", "Elias", "Owen", "Alexander", "Dylan", "Santiago", "Julian", "David", 
    "Joseph", "Matthew", "Luke", "Jackson", "Maverick", "Miles", "Wyatt", 
    "Thomas", "Isaac", "Jacob", "Mason", "Gabriel", "Anthony", "Carter", 
    "Logan", "Aiden", "Grayson", "Caleb", "Cooper", "Charles", "Roman", 
    "Josiah", "Ezekiel", "Thiago", "Isaiah", "Joshua", "Wesley", "Jayden", 
    "Bennett", "Christopher", "Nathan", "Angel", "Nolan", "Waylon", "Cameron", 
    "Brooks", "Andrew", "Beau", "Weston", "Rowan", "Adrian", "Lincoln", "Enzo", 
    "Ian", "Kai", "Christian", "Axel", "Aaron", "Theo", "Silas", "Walker", 
    "Jonathan", "Leonardo", "Everett", "Micah", "Ryan", "August", "Gael", 
    "Robert", "Jose", "Eli", "Jeremiah", "Luka", "Amir", "Jaxon", "Parker", 
    "Colton", "Myles", "Adam", "Atlas", "Xavier", "Easton", "Jordan", "Arthur", 
    "Landon", "Austin", "Dominic", "Adriel", "Damian", "Vincent", "River", 
    "Emiliano", "Jace", "Archer", "Lorenzo", "Jameson", "Nicholas", "Emmett", 
    "Milo", "Harrison", "Giovanni", "Carson", "George", "Kayden", "Jonah", 
    "Greyson", "Hunter", "Graham", "Luis", "Declan", "Sawyer", "Jasper", 
    "Ryder", "Carlos", "Connor", "Juan", "Matteo", "Dawson", "Calvin", "Leon", 
    "Dean", "Evan", "Nathaniel", "Diego", "Arlo", "Bryson", "Jason", "Malachi", 
    "Elliot", "Zion", "Emilio", "Ivan", "Hayden", "Stetson", "Jude", "Legend", 
    "Matias", "Callum", "Hayes", "Jett", "Cole", "Elliott", "Jesus", "Ace", 
    "Beckett", "Alan", "Beckham", "Jayce", "Braxton", "Jaxson", "Amari", 
    "Chase", "Rhett", "Max", "Charlie", "Felix", "Kingston", "Judah", "Antonio", 
    "Emmanuel", "Maxwell", "Ryker", "Alejandro", "Nicolas", "Barrett", "Jesse", 
    "Ashton", "Miguel", "Brayden", "Tyler", "Peter", "Camden", "Zachary", 
    "Tatum", "Kevin", "Andres", "Finn", "Justin", "Tucker", "Bentley", "Zayden", 
    "Messiah", "Abraham", "Alex", "Adonis", "Kaiden", "Timothy", "Knox", "Tate", 
    "Caden", "Ayden", "Nico", "Victor", "Maddox", "Xander", "Oscar", "Colter", 
    "Joel", "Abel", "Patrick", "Rafael", "Griffin", "Brody", "Jaziel", "Rory", 
    "Eithan", "Edward", "Riley", "Brandon", "Milan", "Richard", "Malakai", 
    "Ismael", "Kyrie", "Louis", "Elian", "Kairo", "Cohen", "Nash", "Grant", 
    "Callan", "Dallas", "Harvey", "Muhammad", "Mark", "Javier", "Karter", 
    "Zayn", "Crew", "Eric", "Simon", "Aziel", "Cyrus", "Gavin", "Marcus", 
    "Ronan", "Derek", "Avery", "Omar", "Lane", "Warren", "Lennox", "Paul", 
    "Blake", "Jeremy", "Tristan", "Lukas", "Steven", "Emerson", "Walter", 
    "Cade", "Ellis", "Otto", "Phoenix", "Colt", "Atticus", "Kaleb", "Israel", 
    "Tobias", "Holden", "Saint", "Romeo", "Kenneth", "Jorge", "Angelo", 
    "Remington", "Paxton", "Cody", "Finley", "Kayson", "Koa", "Kash", "Josue", 
    "Ares", "Hendrix", "Bryce", "Maximiliano", "Zyaire", "Reid", "Brian", 
    "Bodhi", "Cruz", "Kaden", "Bryan", "Zane", "Francisco", "Martin", "Brady", 
    "Casey", "Shepherd", "Aidan", "Baker", "Malcolm", "Jax", "Cash", "Clayton", 
    "Kohen", "Leonel", "Cristian", "Bowen", "Dante", "Ali", "Jaylen", "Orion", 
    "Briggs", "Jensen", "Dakota", "Preston", "Maximus", "Gideon", "Erick", 
    "Archie", "Colin", "Sonny", "Shiloh", "Mathias", "Ezequiel", "Sullivan", 
    "Joaquin", "Wade", "King", "Niko", "Damien", "Kade", "Bodie", "Dariel", 
    "Luciano", "Cayden", "Andre", "Manuel", "Fernando", "Colson", "Rhys", 
    "Cairo", "Anderson", "Kyler", "Onyx", "Ibrahim", "Cesar", "Travis", 
    "Santino", "Callahan", "Bradley", "Baylor", "Banks", "Russell", "Desmond", 
    "Killian", "Grady", "Rylan", "Sterling", "Kylo", "Eduardo", "Ricardo", 
    "Wells", "Stephen", "Zander", "Raymond", "Hector", "Eliam", "Edwin", 
    "Titus", "Iker", "Franklin", "Kamari", "Marco", "Spencer", "Julius", 
    "Khalil", "Marshall", "Wilder", "Jared", "Jaden", "Kashton", "Jay", 
    "Karson", "Mario", "Ari", "Remy", "Pedro", "Sergio", "Hugo", "Prince", 
    "Winston", "Pablo", "Forrest", "Augustus", "Kobe", "Oakley", "Daxton", 
    "Tadeo", "Sage", "Apollo", "Lawson", "Kian", "Solomon", "Chance", "Kayce", 
    "Raphael", "Reed", "Jake", "Frederick", "Armani", "Hank", "Nehemiah", 
    "Royal", "Kameron", "Malik", "Alijah", "Kane", "Dalton", "Lewis", "Noel", 
    "Benson", "Sean", "Clark", "Miller", "Kyle", "Kieran", "Sutton", "Fabian", 
    "Tanner", "Marcelo", "Rowen", "Isaias", "Zayne", "Nasir", "Raiden", 
    "Francis", "Bo", "Valentino", "Rome", "Damon", "Reece", "Esteban", "Edgar", 
    "Johnny", "Kylian", "Tyson", "Uriel", "Royce", "Cillian", "Koda", "Kyson", 
    "Eden", "Jalen", "Frank", "Conrad", "Jasiah", "Matthias", "Zaire", "Corbin", 
    "Asa", "Yusuf", "Erik", "Callen", "Kendrick", "Odin", "Brantley", "Rodrigo", 
    "Marcos", "Gianni", "Alexis", "Lucian", "Denver", "Sylas", "Andy", "Collin", 
    "Hezekiah", "Moshe", "Finnegan", "Ronin", "Atreus", "Adan", "Emanuel", 
    "Quinn", "Mack", "Leandro", "Rocco", "Ruben", "Ledger", "Azariah", 
    "Donovan", "Moses", "Kaizen", "Elio", "Leonidas", "Lawrence", "Tripp", 
    "Ariel", "Alonzo", "Kaison", "Lian", "Devin", "Rio", "Johnathan", "Ayaan", 
    "Gunner", "Jeffrey", "Philip", "Samson", "Moises", "Lucca", "Musa", 
    "Camilo", "Hamza", "Ridge", "Kolton", "Morgan", "Troy", "Kylan", "Amiri", 
    "Boone", "Makai", "Johan", "Bruce", "Dorian", "Gregory", "Pierce", "Roy", 
    "Drew", "Clay", "Caiden", "Enrique", "Jamir", "Leland", "Mohamed", 
    "Alessandro", "Deacon", "Augustine", "Dominick", "Roberto", "Kasen", 
    "Zain", "Jonas", "Emir", "Seth", "Saul", "Jamari", "Lionel", "Garrett", 
    "Jaiden", "Fletcher", "Scott", "Armando", "Cassius", "Kason", "Zachariah", 
    "Ford", "Soren", "Zaiden", "Allen", "Louie", "Ronald", "Alden", "Arturo", 
    "Caspian", "Rayan", "Major", "Arjun", "Colby", "Eliel", "Krew", "Ander", 
    "Kenzo", "Maximilian", "Memphis", "Nikolai", "Samir", "Ocean", "Anakin", 
    "Gerardo", "Keegan", "Maximo", "Mohammed", "Kaysen", "Julio", "Mohammad", 
    "Gunnar", "Shane", "Ozzy", "Zakai", "Sincere", "Jaime", "Albert", "Azriel", 
    "Izaiah", "Jaxton", "Raul", "Yosef", "Creed", "Rhodes", "Princeton", 
    "Porter", "Cassian", "Omari", "Tru", "Chosen", "Reese", "Jayceon", "Jayson", 
    "Jamie", "Reign", "Trevor", "Phillip", "Boston", "Kamden", "Crue", "Eliseo", 
    "Colsen", "Keanu", "Mauricio", "Salem", "Dario", "Dax", "Jase", "Shawn", 
    "Vicente", "Gustavo", "Danny", "Mylo", "Kyro", "Wilson", "Davis", "Jakari", 
    "Jakai", "Truett", "Hassan", "Chris", "Sam", "Brixton", "Kyaire", "Uriah", 
    "Azael", "Westley", "Rocky", "Peyton", "Sevyn", "Dilan", "Drake", "Zaid", 
    "Roland", "Dereck", "Braylen", "Harlan", "Taylor", "Riggs", "Ahmad", "Cal", 
    "Marvin", "Donald", "Leonard", "Nathanael", "Aarav", "Abdiel", "Kareem", 
    "Corey", "Emmitt", "Wylder", "Koen", "Junior", "Zyair", "Zayd", "Dustin", 
    "Wayne", "Ahmed", "Madden", "Quincy", "Bellamy", "Lachlan", "Layton", 
    "Amias", "Chaim", "Layne", "Mac", "Amos", "Briar", "Carmelo", "Aries", 
    "Bruno", "Houston", "Julien", "Trace", "Brock", "Yahya", "Conor", "Dennis", 
    "Duke", "Abram", "Jefferson", "Vincenzo", "Izan", "Lee", "Finnley", 
    "Brayan", "Raylan", "Enoch", "Avyaan", "Dexter", "Salvador", "Case", 
    "Misael", "Forest", "Nikolas", "Westin", "Braylon", "Clyde", "Ryland", 
    "Otis", "Tommy", "Zeke", "Yehuda", "Tomas", "Azrael", "Dutton", "Flynn", 
    "Chandler", "Idris", "Zamir", "Ambrose", "Franco", "Huxley", "Wes", 
    "Chozen", "Darius", "Valentin", "Alberto", "Magnus", "Roger", "Benicio", 
    "Brycen", "Marcel", "Ryatt", "Zahir", "Keith", "Rayden", "Jamison", "Teo", 
    "Skyler", "Blaze", "Cayson", "Hugh", "Yahir", "Cannon", "Yousef", "Bjorn", 
    "Noe", "Alonso", "Alvaro", "Evander", "Kenai", "Aurelio", "Jahmir", 
    "Lochlan", "Aron", "Harry", "Nelson", "Ray", "Alfredo", "Abdullah", "Aryan", 
    "Conner", "Lennon", "Bridger", "Westyn", "Jasiel", "Quentin", "Trey", 
    "Yael", "Alvin", "Casen", "Dakari", "Rex", "Damir", "Waylen", "Izael", 
    "Jeremias", "Kaiser", "Kolson", "Ben", "Kyree", "Tony", "Bode", "Jesiah", 
    "Eiden", "Jaxxon", "Jedidiah", "Remi", "Robin", "Santana", "Kyren", 
    "Landen", "Ezrah", "Murphy", "Castiel", "Boden", "Derrick", "Karim", 
    "Mustafa", "Rey", "Rudy", "Emery", "Ignacio", "Jettson", "Bear", "Edison", 
    "Ricky", "Ramon", "Anders", "Gage", "Guillermo", "Kolter", 
    "Quinton", "Axton", "Abner", "Alfred", "Darwin", "Rohan", "Lance", "Avi", 
    "Keaton", "Orlando", "Everest", "Jagger", "Elisha", "Heath", "Jones", 
    "Thaddeus", "Allan", "Cason", "Douglas", "Issac", "Kenji", "Matheo", "Ty", 
    "Asaiah", "Jimmy", "Arian", "Ozias", "Leroy", "Neil", "Watson", "Agustin", 
    "Bryer", "Jerry", "Dillon", "Eren", "Eugene", "Ayan", "Melvin", "Nixon", 
    "Reuben", "Stanley", "Grey", "Loyal", "Alec", "Casper", "Dane", "Azaiah", 
    "Byron", "Joe", "Emory", "Zaylen", "Massimo", "Trenton", "Gatlin", "Joey", 
    "Benny", "Jon", "Jrue", "Gian", "Seven", "Colten", "Ernesto", "Fisher", 
    "Teddy", "Kaisen", "Zechariah", "Darian", "Salvatore", "Jericho", 
    "Mitchell", "Alistair", "Calum", "Van", "Zev", "Langston", "Mccoy", 
    "Ulises", "Lucien", "Benedict", "Carlo", "Coleson", "Meir", "Henrik", 
    "Jiraiya", "Kellan", "Alfonso", "Azai", "Campbell", "Kylen", "Felipe", 
    "Leif", "Rowdy", "Curtis", "Ameer", "Kiaan", "Maurice", "Krue", "Shimon", 
    "Zyon", "Damari", "Jairo", "Khalid", "Kabir", "Jireh", "Mathew", "Shepard", 
    "Eddie", "Isael", "Arden", "Cedric", "Nazir", "Alessio", "Khai", 
    "Marcellus", "Wesson", "Yisroel", "Zymir", "Landyn", "Darren", "Legacy", 
    "Devon", "Judson", "Vihaan", "Yitzchok", "Zen", "Dangelo", "Adler", "Aspen", 
    "Brodie", "Kase", "Khaza", "Mordechai", "Dash", "Makari", "Neo", "Zavier", 
    "Evren", "Imran", "Laith", "Cain", "Ira", "Osiris", "Shlomo", "Yaakov", 
    "Ephraim", "Shmuel", "Wallace", "Yeshua", "Kannon", "Kingsley", "Noa", 
    "TRUE", "Ermias", "Harold", "Joziah", "Rene", "Truce", "Aldo", "Dimitri", 
    "Halo", "Ronnie", "Vance", "Aden", "Ishaan", "Kace", "Stefan"
]

first_names_female = [
    "Olivia", "Emma", "Amelia", "Charlotte", "Mia", "Sophia", "Isabella", 
    "Evelyn", "Ava", "Sofia", "Camila", "Harper", "Luna", "Eleanor", "Violet", 
    "Aurora", "Elizabeth", "Eliana", "Hazel", "Chloe", "Ellie", "Nora", 
    "Gianna", "Lily", "Emily", "Aria", "Scarlett", "Penelope", "Zoe", "Ella", 
    "Avery", "Abigail", "Mila", "Lucy", "Isla", "Ivy", "Layla", "Lainey", 
    "Nova", "Grace", "Willow", "Riley", "Emilia", "Naomi", "Elena", 
    "Madison", "Valentina", "Victoria", "Stella", "Delilah", "Maya", "Hannah", 
    "Leah", "Lillian", "Genesis", "Josephine", "Sadie", "Adeline", "Zoey", 
    "Sophie", "Paisley", "Alice", "Ruby", "Eloise", "Madelyn", "Leilani", 
    "Claire", "Addison", "Ayla", "Emery", "Iris", "Eden", "Natalie", "Maria", 
    "Maeve", "Daisy", "Vivian", "Clara", "Autumn", "Liliana", "Everly", 
    "Audrey", "Lyla", "Jade", "Kinsley", "Millie", "Madeline", "Josie", 
    "Kennedy", "Athena", "Melody", "Caroline", "Aaliyah", "Anna", "Sarah", 
    "Quinn", "Lydia", "Lucia", "Allison", "Hailey", "Ailany", "Cora", 
    "Ariana", "Parker", "Natalia", "Gabriella", "Savannah", "Brooklyn", 
    "Bella", "Georgia", "Juniper", "Alaia", "Raelynn", "Hadley", "Rose", 
    "Julia", "Serenity", "Eliza", "Margaret", "Eva", "Amara", "Melanie", 
    "Cecilia", "Ashley", "Rylee", "Margot", "Samantha", "Catalina", 
    "Juliette", "Aubrey", "Esther", "Mary", "Nevaeh", "Skylar", "Alina", 
    "Amira", "Ember", "Magnolia", "Sienna", "Charlie", "Elliana", "Summer", 
    "Alana", "Brielle", "Remi", "Sage", "Valerie", "Hallie", "Wrenley", 
    "Kehlani", "Emerson", "June", "Sloane", "Emersyn", "Elsie", "Oaklynn", 
    "Oakley", "Blakely", "Freya", "Piper", "Valeria", "Arya", "Adalynn", 
    "Everleigh", "Genevieve", "Anastasia", "Isabel", "Peyton", "Amaya", 
    "Isabelle", "Olive", "Ruth", "Ximena", "Evangeline", "Katherine", 
    "Callie", "Rosalie", "Alani", "Lilah", "Kaia", "Brianna", "Bailey", 
    "Phoebe", "Vivienne", "Andrea", "Myla", "Lia", "Sara", "Kylie", "Reese", 
    "Annie", "Daphne", "Ada", "Adaline", "Arianna", "Ariella", "Sutton", 
    "Celeste", "Jasmine", "Mackenzie", "Haven", "Scottie", "Gemma", "Ana", 
    "Tatum", "Arabella", "Lila", "Molly", "Stevie", "Blake", "Aitana", 
    "Alaina", "Wren", "River", "Noelle", "Delaney", "Journee", "Blair", 
    "Adalyn", "Kaylee", "Alexandra", "Mabel", "Norah", "Presley", "Alora", 
    "Vera", "Celine", "Amy", "Brynlee", "Nyla", "Saylor", "Khloe", 
    "Antonella", "Zara", "Aliyah", "Cataleya", "Lennon", "Kiara", "Camille", 
    "Dahlia", "Kaylani", "Mariana", "Diana", "Reagan", "Selena", "Kimberly", 
    "Rachel", "Gracie", "Faith", "Juliana", "Miriam", "Elise", "Noa", 
    "Elaina", "Maisie", "Lilith", "Collins", "Palmer", "Lilly", "Shiloh", 
    "Ophelia", "Elianna", "Lena", "Harmony", "Aspen", "Rowan", "Gia", "Leila", 
    "Jane", "Talia", "Adelaide", "Dakota", "Lola", "Lucille", "Kailani", 
    "Morgan", "Zuri", "Milani", "Daniela", "Selah", "Alessia", "Angela", 
    "Juliet", "Evie", "Amora", "Rory", "Marley", "Sydney", "Alanna", "Leia", 
    "Luciana", "Kamila", "Harlow", "Kali", "Octavia", "Amari", "Sawyer", 
    "Gabriela", "Ariel", "Maggie", "Rosemary", "Ryleigh", "Tessa", 
    "Evelynn", "Londyn", "Danna", "Amina", "Brooke", "Samara", "Kendall", 
    "Rosie", "Alayna", "Angelina", "Francesca", "Adelyn", "Fatima", "Hope", 
    "Nicole", "Nayeli", "Catherine", "Nina", "Journey", "Adriana", "Camilla", 
    "Ailani", "Malia", "Meadow", "Jordyn", "Joanna", "Emory", "Malani", 
    "Serena", "Teagan", "Aurelia", "Vanessa", "Kayla", "Navy", "Poppy", 
    "Kalani", "Regina", "Adelina", "Rebecca", "Ariyah", "Esme", "Heidi", 
    "Aisha", "Julieta", "Thea", "Annabelle", "Esmeralda", "Lauren", 
    "Julianna", "Taylor", "Wrenlee", "London", "Giselle", "Sabrina", 
    "Azalea", "Laura", "Sylvie", "Sylvia", "Alaya", "Raya", "Elora", 
    "Finley", "Mya", "Dream", "Viviana", "Elaine", "Elodie", "Laila", 
    "Sunny", "Briella", "Lana", "Paige", "Itzel", "Mckenna", "Melissa", 
    "Frances", "Mira", "Payton", "Hattie", "Astrid", "Brynn", "Winter", 
    "Aylin", "Miley", "Raven", "Jocelyn", "Maryam", "Logan", "Veronica", 
    "Gwendolyn", "Anya", "Leighton", "Alivia", "Harley", "Charlee", "Alyssa", 
    "Colette", "Hayden", "Lorelai", "Jayla", "Ivory", "Anaya", "Fiona", 
    "Trinity", "Aubree", "Michelle", "Matilda", "Lilliana", "Mallory", 
    "Mariah", "Helena", "Wynter", "Carmen", "Alayah", "Liana", "Holly", 
    "Madilyn", "Phoenix", "Raelyn", "Willa", "Helen", "Emely", "Alessandra", 
    "Gracelynn", "Carolina", "Arleth", "Salem", "Dorothy", "Xiomara", 
    "Elisa", "Reign", "Florence", "Alicia", "Madeleine", "Melany", 
    "Katalina", "Zariah", "Bonnie", "Joy", "Kaliyah", "Haisley", "Sarai", 
    "Blaire", "Elowyn", "Saige", "Adelynn", "Opal", "Demi", "Nylah", "Emmy", 
    "Camryn", "Kira", "Lorelei", "Daleyza", "Raegan", "Maia", "Bianca", 
    "Aniyah", "Annalise", "Alexandria", "Amirah", "Alison", "Anahi", 
    "Gracelyn", "Brooklynn", "Miracle", "Everlee", "Adhara", "Alma", "Macie", 
    "Murphy", "Romina", "Cassidy", "Clementine", "Heaven", "Elle", "Skye", 
    "Destiny", "Lyra", "Rylie", "Paris", "Cameron", "Felicity", "Maddison", 
    "Leona", "Scarlet", "Kora", "Mariam", "Meredith", "Mckenzie", "Dayana", 
    "Cali", "Amanda", "Arielle", "Angel", "Calliope", "Fernanda", "Estella", 
    "April", "Izabella", "Hanna", "Marceline", "Alexis", "Carter", 
    "Daniella", "Marlee", "Virginia", "Kataleya", "Halo", "Nadia", "Amiyah", 
    "Madelynn", "Emerie", "Renata", "Oaklee", "Remington", "Maxine", 
    "Nellie", "Briar", "Danielle", "Charli", "Makenna", "Imani", "Armani", 
    "Edith", "Nalani", "Mae", "Vienna", "Hadassah", "Stephanie", "Ari", 
    "Kate", "Jimena", "Briana", "Faye", "Jordan", "Louise", "Amber", 
    "Makayla", "Zahra", "Lylah", "Margo", "Amoura", "Jennifer", "Kyla", 
    "Mylah", "Winnie", "Alisson", "Amalia", "Reina", "Avianna", "Allie", 
    "Ivanna", "Ariya", "Lilian", "Alia", "Aylani", "Noah", "Reyna", "Lexi", 
    "Brinley", "Iyla", "Mavis", "Lina", "Cecelia", "Eve", "Maren", "Monroe", 
    "Capri", "Emelia", "Jessica", "Halle", "Alejandra", "Gabrielle", "Yara", 
    "Beatrice", "Della", "Kamryn", "Katie", "Ariah", "Arlette", "Noemi", 
    "Alondra", "Maliyah", "Mara", "Jacqueline", "Jazlyn", "Frankie", "Angie", 
    "Eileen", "Lyric", "Aliana", "Sierra", "Rosalia", "Oaklyn", "Chaya", 
    "Amaia", "Leyla", "Holland", "Cleo", "Jream", "Leslie", "Sevyn", 
    "Jolene", "Mina", "Keira", "Legacy", "Tiana", "Elliott", "Cassandra", 
    "Jaylani", "Priscilla", "Rhea", "Kinley", "Clover", "Estrella", 
    "Zariyah", "Journi", "Miranda", "Angelica", "Marlowe", "Jovie", "Abby", 
    "Sariyah", "Kenzie", "Oakleigh", "Aya", "Siena", "Emberly", "Melina", 
    "Amani", "Bristol", "Estelle", "Galilea", "Irene", "Marie", "Marina", 
    "Makenzie", "Sasha", "Paislee", "Isabela", "Goldie", "Myra", "Davina", 
    "Flora", "Anne", "Azariah", "Indie", "Kaitlyn", "Jazmin", "Gloria", 
    "Georgina", "Shelby", "Dallas", "Thalia", "Aliza", "Averie", "Skyler", 
    "Macy", "Rosa", "Dulce", "Khaleesi", "Marilyn", "Martha", "Adley", 
    "Belen", "Ellianna", "Kelsey", "Nia", "Chana", "Lakelynn", "Selene", 
    "Lottie", "Loretta", "Aleena", "Ila", "Dani", "Remy", "Whitley", 
    "Jenna", "Lillie", "Kennedi", "Violeta", "Kendra", "Lennox", "Laney", 
    "Aviana", "Solana", "Veda", "Marigold", "Billie", "Drew", "Dylan", 
    "Ellis", "Gwen", "Amayah", "Milan", "Leilany", "Ryan", "Bridget", 
    "Christina", "Ezra", "Ainsley", "Emerald", "Hana", "Noor", "Rivka", 
    "Amelie", "Jenesis", "Royalty", "Lenora", "Taytum", "Jamie", "Kathryn", 
    "Aileen", "Arlet", "Coraline", "Kiana", "Kyra", "Araceli", "Azaria", 
    "Kenna", "Monica", "Bethany", "Laurel", "Charley", "Karla", "Kayleigh", 
    "Rayna", "Louisa", "Celia", "Emmie", "Fallon", "Persephone", "Winona", 
    "Marisol", "Lara", "Kensley", "Mckinley", "Michaela", "Novalee", 
    "Elyse", "Lacey", "Penny", "Zelda", "Alena", "Luz", "Keilani", "Nala", 
    "Paula", "Birdie", "Karsyn", "Lakelyn", "Miller", "Jemma", "Aleah", 
    "Inaya", "Megan", "Sloan", "Charleigh", "Rosalina", "Andi", "Nola", 
    "Julie", "Adrianna", "Kaeli", "Addilyn", "Freyja", "Ramona", "Samira", 
    "Karina", "Denver", "Janelle", "Mikayla", "Seraphina", "Haley", "Indy", 
    "Paulina", "Rowyn", "Milana", "Chelsea", "Elina", "Milena", "Valery", 
    "Ivey", "Maci", "Stormi", "Brittany", "Madilynn", "Aila", "Yareli", 
    "Yaretzi", "Zaylee", "Erin", "Adele", "Robin", "Jaliyah", "Maisy", 
    "Pearl", "Adalee", "Brynleigh", "Keyla", "Alexa", "Baylor", "Jessie", 
    "Cielo", "Braelynn", "Alianna", "Theodora", "Malaya", "Meilani", 
    "Tallulah", "Analia", "Nyomi", "Promise", "Sol", "Xyla", "Kylee", 
    "Marjorie", "Treasure", "Soleil", "Zaria", "Cynthia", "Luella", "Sky", 
    "Ayleen", "Neriah", "Iliana", "Judith", "Ocean", "Lea", "Linda", "Livia", 
    "Maddie", "Magdalena", "Elia", "Kahlani", "Micah", "Tiffany", 
    "Wrenleigh", "Zaniyah", "Kallie", "Love", "Andie", "Johanna", "Mercy", 
    "Skyla", "Aliya", "Deborah", "Zainab", "Anais", "Greta", "Kaiya", 
    "Malaysia", "Marianna", "Amaris", "Barbara", "Bellamy", "Dalia", "Anika", 
    "Giana", "Keziah", "Nataly", "Cheyenne", "Kelly", "Luisa", "Salma", 
    "Teresa", "Aura", "Carly", "Liv", "Azari", "Dafne", "Rebekah", "Amiri", 
    "Berkley", "Emberlynn", "Hunter", "Jaycee", "Alexia", "Reya", "Ruthie", 
    "Eleanora", "Janiyah", "Rosalyn", "Giuliana", "Emiliana", "Novah", "Tru", 
    "Kori", "Aspyn", "Chandler", "Kailany", "Lilyana", "Elowen", "Khalani", 
    "Naya", "Zyla", "Jolie", "Leanna", "Yamileth", "Cattleya", "Elisabeth", 
    "Ensley", "Ashlyn", "Allyson", "August", "Kimber", "Marleigh", "Soraya", 
    "Anaiah", "Analeia", "Waverly", "Yasmin", "Zora", "Joelle", "Lilia", 
    "Nancy", "Icelynn", "Indigo", "Arely", "Laylani", "Romy", "Scout", 
    "Ayra", "Giovanna", "Siya", "Katelyn", "Madalyn", "Natasha", "Alaiya", 
    "Honey", "Lettie", "Sarahi", "Elsa", "Emmeline", "Hadlee", "Lilianna", 
    "Zendaya", "Ainhoa", "Elliot", "Jazmine", "Aadhya", "Guinevere", "Rayne", 
    "Clare", "Saanvi", "Campbell", "Salome", "Tilly", "Yusra", "Akira", 
    "Henley", "Lyanna", "Quincy", "Rosalee", "Vada", "Ainara", "Annika", 
    "Ayah", "Violette", "Aleia", "Kaya", "Mazie", "Amyra", "Celina", 
    "Mikaela", "Paloma", "Elouise", "Etta", "Julietta", "Kamiyah", "Zoya", 
    "Jayleen", "Kassidy", "Keily", "Harlee", "Kiera", "Liberty", "Darcy", 
    "Dior", "Lisa", "Malka", "Arisbeth", "Kara", "Bailee", "Elani", 
    "Harmoni", "Mariella", "Zayla", "Emi", "Jianna", "Maelynn", "Avani", 
    "Lavender", "Karter", "Raina"
]

last_names = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", 
    "Davis", "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", 
    "Wilson", "Anderson", "Thomas", "Taylor", "Moore", "Jackson", "Martin", 
    "Lee", "Perez", "Thompson", "White", "Harris", "Sanchez", "Clark", 
    "Ramirez", "Lewis", "Robinson", "Walker", "Young", "Allen", "King", 
    "Wright", "Scott", "Torres", "Nguyen", "Hill", "Flores", "Green", 
    "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell", "Mitchell", 
    "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz", 
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", 
    "Morales", "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", 
    "Cooper", "Peterson", "Bailey", "Reed", "Kelly", "Howard", "Ramos", 
    "Kim", "Cox", "Ward", "Richardson", "Watson", "Brooks", "Chavez", 
    "Wood", "James", "Bennett", "Gray", "Mendoza", "Ruiz", "Hughes", 
    "Price", "Alvarez", "Castillo", "Sanders", "Patel", "Myers", "Long", 
    "Ross", "Foster", "Jimenez", "Powell", "Jenkins", "Perry", "Russell", 
    "Sullivan", "Bell", "Coleman", "Butler", "Henderson", "Barnes", 
    "Gonzales", "Fisher", "Vasquez", "Simmons", "Romero", "Jordan", 
    "Patterson", "Alexander", "Hamilton", "Graham", "Reynolds", "Griffin", 
    "Wallace", "Moreno", "West", "Cole", "Hayes", "Bryant", "Herrera", 
    "Gibson", "Ellis", "Tran", "Medina", "Aguilar", "Stevens", "Murray", 
    "Ford", "Castro", "Marshall", "Owens", "Harrison", "Fernandez", 
    "Mcdonald", "Woods", "Washington", "Kennedy", "Wells", "Vargas", 
    "Henry", "Chen", "Freeman", "Webb", "Tucker", "Guzman", "Burns", 
    "Crawford", "Olson", "Simpson", "Porter", "Hunter", "Gordon", "Mendez", 
    "Silva", "Shaw", "Snyder", "Mason", "Dixon", "Munoz", "Hunt", "Hicks", 
    "Holmes", "Palmer", "Wagner", "Black", "Robertson", "Boyd", "Rose", 
    "Stone", "Salazar", "Fox", "Warren", "Mills", "Meyer", "Rice", 
    "Schmidt", "Garza", "Daniels", "Ferguson", "Nichols", "Stephens", 
    "Soto", "Weaver", "Ryan", "Gardner", "Payne", "Grant", "Dunn", "Kelley", 
    "Spencer", "Hawkins", "Arnold", "Pierce", "Vazquez", "Hansen", "Peters", 
    "Santos", "Hart", "Bradley", "Knight", "Elliott", "Cunningham", 
    "Duncan", "Armstrong", "Hudson", "Carroll", "Lane", "Riley", "Andrews", 
    "Alvarado", "Ray", "Delgado", "Berry", "Perkins", "Hoffman", "Johnston", 
    "Matthews", "Pena", "Richards", "Contreras", "Willis", "Carpenter", 
    "Lawrence", "Sandoval", "Guerrero", "George", "Chapman", "Rios", 
    "Estrada", "Ortega", "Watkins", "Greene", "Nunez", "Wheeler", "Valdez", 
    "Harper", "Burke", "Larson", "Santiago", "Maldonado", "Morrison", 
    "Franklin", "Carlson", "Austin", "Dominguez", "Carr", "Lawson", 
    "Jacobs", "Obrien", "Lynch", "Singh", "Vega", "Bishop", "Montgomery", 
    "Oliver", "Jensen", "Harvey", "Williamson", "Gilbert", "Dean", "Sims", 
    "Espinoza", "Howell", "Li", "Wong", "Reid", "Hanson", "Le", "Mccoy", 
    "Garrett", "Burton", "Fuller", "Wang", "Weber", "Welch", "Rojas", 
    "Lucas", "Marquez", "Fields", "Park", "Yang", "Little", "Banks", 
    "Padilla", "Day", "Walsh", "Bowman", "Schultz", "Luna", "Fowler", 
    "Mejia", "Davidson", "Acosta", "Brewer", "May", "Holland", "Juarez", 
    "Newman", "Pearson", "Curtis", "Cortez", "Douglas", "Schneider", 
    "Joseph", "Barrett", "Navarro", "Figueroa", "Keller", "Avila", "Wade", 
    "Molina", "Stanley", "Hopkins", "Campos", "Barnett", "Bates", "Chambers", 
    "Caldwell", "Beck", "Lambert", "Miranda", "Byrd", "Craig", "Ayala", 
    "Lowe", "Frazier", "Powers", "Neal", "Leonard", "Gregory", "Carrillo", 
    "Sutton", "Fleming", "Rhodes", "Shelton", "Schwartz", "Norris", 
    "Jennings", "Watts", "Duran", "Walters", "Cohen", "Mcdaniel", "Moran", 
    "Parks", "Steele", "Vaughn", "Becker", "Holt", "Deleon", "Barker", 
    "Terry", "Hale", "Leon", "Hail", "Benson", "Haynes", "Horton", "Miles", 
    "Lyons", "Pham", "Graves", "Bush", "Thornton", "Wolfe", "Warner", 
    "Cabrera", "Mckinney", "Mann", "Zimmerman", "Dawson", "Lara", "Fletcher", 
    "Page", "Mccarthy", "Love", "Robles", "Cervantes", "Solis", "Erickson", 
    "Reeves", "Chang", "Klein", "Salinas", "Fuentes", "Baldwin", "Daniel", 
    "Simon", "Velasquez", "Hardy", "Higgins", "Aguirre", "Lin", "Cummings", 
    "Chandler", "Sharp", "Barber", "Bowen", "Ochoa", "Dennis", "Robbins", 
    "Liu", "Ramsey", "Francis", "Griffith", "Paul", "Blair", "Oconnor", 
    "Cardenas", "Pacheco", "Cross", "Calderon", "Quinn", "Moss", "Swanson", 
    "Chan", "Rivas", "Khan", "Rodgers", "Serrano", "Fitzgerald", "Rosales", 
    "Stevenson", "Christensen", "Manning", "Gill", "Curry", "Mclaughlin", 
    "Harmon", "Mcgee", "Gross", "Doyle", "Garner", "Newton", "Burgess", 
    "Reese", "Walton", "Blake", "Trujillo", "Adkins", "Brady", "Goodman", 
    "Roman", "Webster", "Goodwin", "Fischer", "Huang", "Potter", "Delacruz", 
    "Montoya", "Todd", "Wu", "Hines", "Mullins", "Castaneda", "Malone", 
    "Cannon", "Tate", "Mack", "Sherman", "Hubbard", "Hodges", "Zhang", 
    "Guerra", "Wolf", "Valencia", "Franco", "Saunders", "Rowe", "Gallagher", 
    "Farmer", "Hammond", "Hampton", "Townsend", "Ingram", "Wise", 
    "Gallegos", "Clarke", "Barton", "Schroeder", "Maxwell", "Waters", 
    "Logan", "Camacho", "Strickland", "Norman", "Person", "Colon", 
    "Parsons", "Frank", "Harrington", "Glover", "Osborne", "Buchanan", 
    "Casey", "Floyd", "Patton", "Ibarra", "Ball", "Tyler", "Suarez", 
    "Bowers", "Orozco", "Salas", "Cobb", "Gibbs", "Andrade", "Bauer", 
    "Conner", "Moody", "Escobar", "Mcguire", "Lloyd", "Mueller", "Hartman", 
    "French", "Kramer", "Mcbride", "Pope", "Lindsey", "Velazquez", "Norton", 
    "Mccormick", "Sparks", "Flynn", "Yates", "Hogan", "Marsh", "Macias", 
    "Villanueva", "Zamora", "Pratt", "Stokes", "Owen", "Ballard", "Lang", 
    "Brock", "Villarreal", "Charles", "Drake", "Barrera", "Cain", "Patrick", 
    "Pineda", "Burnett", "Mercado", "Santana", "Shepherd", "Bautista", 
    "Ali", "Shaffer", "Lamb", "Trevino", "Mckenzie", "Hess", "Beil", 
    "Olsen", "Cochran", "Morton", "Nash", "Wilkins", "Petersen", "Briggs", 
    "Shah", "Roth", "Nicholson", "Holloway", "Lozano", "Flowers", "Rangel", 
    "Hoover", "Arias", "Short", "Mora", "Valenzuela", "Bryan", "Meyers", 
    "Weiss", "Underwood", "Bass", "Greer", "Summers", "Houston", "Carson", 
    "Morrow", "Clayton", "Whitaker", "Decker", "Yoder", "Collier", "Zuniga", 
    "Carey", "Wilcox", "Melendez", "Poole", "Roberson", "Larsen", "Conley", 
    "Davenport", "Copeland", "Massey", "Lam", "Huff", "Rocha", "Cameron", 
    "Jefferson", "Hood", "Monroe", "Anthony", "Pittman", "Huynh", 
    "Randall", "Singleton", "Kirk", "Combs", "Mathis", "Christian", 
    "Skinner", "Bradford", "Richard", "Galvan", "Wall", "Boone", "Kirby", 
    "Wilkinson", "Bridges", "Bruce", "Atkinson", "Velez", "Meza", "Roy", 
    "Vincent", "York", "Hodge", "Villa", "Abbott", "Allison", "Tapia", 
    "Gates", "Chase", "Sosa", "Sweeney", "Farrell", "Wyatt", "Dalton", 
    "Horn", "Barron", "Phelps", "Yu", "Dickerson", "Heath", "Foley", 
    "Atkins", "Mathews", "Bonilla", "Acevedo", "Benitez", "Zavala", 
    "Hensley", "Glenn", "Cisneros", "Harrell", "Shields", "Rubio", "Choi", 
    "Huffman", "Boyer", "Garrison", "Arroyo", "Bond", "Kane", "Hancock", 
    "Callahan", "Dillon", "Cline", "Wiggins", "Grimes", "Arellano", 
    "Melton", "Oneill", "Savage", "Ho", "Beltran", "Pitts", "Parrish", 
    "Ponce", "Rich", "Booth", "Koch", "Golden", "Ware", "Brennan", 
    "Mcdowell", "Marks", "Cantu", "Humphrey", "Baxter", "Sawyer", "Clay", 
    "Tanner", "Hutchinson", "Kaur", "Berg", "Wiley", "Gilmore", "Russo", 
    "Villegas", "Hobbs", "Keith", "Wilkerson", "Ahmed", "Beard", "Mcclain", 
    "Montes", "Mata", "Rosario", "Vang", "S", "Walter", "Henson", 
    "Oneal", "Mosley", "Mcclure", "Beasley", "Stephenson", "Snow", "Huerta", 
    "Preston", "Vance", "Barry", "Johns", "Eaton", "Blackwell", "Dyer", 
    "Prince", "Macdonald", "Solomon", "Guevara", "Stafford", "English", 
    "Hurst", "Woodard", "Cortes", "Shannon", "Kemp", "Nolan", "Mccullough", 
    "Merritt", "Murillo", "Moon", "Salgado", "Strong", "Kline", "Cordova", 
    "Barajas", "Roach", "Rosas", "Winters", "Jacobson", "Lester", "Knox", 
    "Bullock", "Kerr", "Leach", "Meadows", "Davila", "Orr", "Whitehead", 
    "Pruitt", "Kent", "Conway", "Mckee", "Barr", "David", "Dejesus", 
    "Marin", "Berger", "Mcintyre", "Blankenship", "Gaines", "Palacios", 
    "Cuevas", "Bartlett", "Durham", "Dorsey", "Mccall", "Odonnell", 
    "Stein", "Browning", "Stout", "Lowery", "Sloan", "Mclean", "Hendricks", 
    "Calhoun", "Sexton", "Chung", "Gentry", "Hull", "Duarte", "Ellison", 
    "Nielsen", "Gillespie", "Buck", "Middleton", "Sellers", "Leblanc", 
    "Esparza", "Hardin", "Bradshaw", "Mcintosh", "Howe", "Livingston", 
    "Frost", "Glass", "Morse", "Knapp", "Herman", "Stark", "Bravo", 
    "Noble", "Spears", "Weeks", "Corona", "Frederick", "Buckley", 
    "Mcfarland", "Hebert", "Enriquez", "Hickman", "Quintero", "Randolph", 
    "Schaefer", "Walls", "Trejo", "House", "Reilly", "Pennington", 
    "Michael", "Conrad", "Giles", "Benjamin", "Crosby", "Fitzpatrick", 
    "Donovan", "Mays", "Mahoney", "Valentine", "Raymond", "Medrano", 
    "Hahn", "Mcmillan", "Small", "Bentley", "Felix", "Peck", "Lucero", 
    "Boyle", "Hanna", "Pace", "Rush", "Hurley", "Harding", "Mcconnell", 
    "Bernal", "Nava", "Ayers", "Everett", "Ventura", "Avery", "Pugh", 
    "Mayer", "Bender", "Shepard", "Mcmahon", "Landry", "Case", "Sampson", 
    "Moses", "Magana", "Blackburn", "Dunlap", "Gould", "Duffy", "Vaughan", 
    "Herring", "Mckay", "Espinosa", "Rivers", "Farley", "Bernard", 
    "Ashley", "Friedman", "Potts", "Truong", "Costa", "Correa", "Blevins", 
    "Nixon", "Clements", "Fry", "Delarosa", "Best", "Benton", "Lugo", 
    "Portillo", "Dougherty", "Crane", "Haley", "Phan", "Villalobos", 
    "Blanchard", "Horne", "Finley", "Quintana", "Lynn", "Esquivel", 
    "Bean", "Dodson", "Mullen", "Xiong", "Hayden", "Cano", "Levy", 
    "Huber", "Richmond", "Moyer", "Lim", "Frye", "Sheppard", "Mccarty", 
    "Avalos", "Booker", "Waller", "Parra", "Woodward", "Jaramillo", 
    "Krueger", "Rasmussen", "Brandt", "Peralta", "Donaldson", "Stuart", 
    "Faulkner", "Maynard", "Galindo", "Coffey", "Estes", "Sanford", 
    "Burch", "Maddox", "Vo", "Oconnell", "Vu", "Andersen", 
    "Spence", "Mcpherson", "Church", "Schmitt", "Stanton", "Leal", 
    "Cherry", "Compton", "Dudley", "Sierra", "Pollard", "Alfaro", "Hester", 
    "Proctor", "Lu", "Hinton", "Novak", "Good", "Madden", "Mccann", 
    "Terrell", "Jarvis", "Dickson", "Reyna", "Cantrell", "Mayo", "Branch", 
    "Hendrix", "Rollins", "Rowland", "Whitney", "Duke", "Odom", 
    "Daugherty", "Travis", "Tang"
]

ziodiac_sign = ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Libra', 'Scorpio', 'Sagittarius', 
    'Capricorn', 'Aquarius', 'Pisces']

religion = ['Christianity', 'Islam', 'Hinduism', 'Buddhism', 'Judaism', 'Sikhism', 'Bahá\'í Faith', 'Shinto',
    'Confucianism', 'Jainism', 'Taoism', 'Zoroastrianism', 'Paganism', 'Unitarian Universalism', 'Wicca', 'Baháʼí Faith']


##==========================PHYSICAL APPEARANCE======================================##
favorite_color = [
    "red", "blue", "green", "yellow", "orange", "purple", "pink", "brown",
    "black", "white", "gray", "grey", "cyan", "magenta", "lime", "navy",
    "maroon", "olive", "teal", "silver", "gold", "violet",
    "crimson", "scarlet", "ruby", "cherry", "rose", "coral", "tomato",
    "brick", "burgundy", "wine", "mahogany", "rust", "vermilion", "rouge",
    "azure", "cerulean", "cobalt", "sapphire", "indigo", "navy", "sky",
    "steel", "turquoise", "aqua", "aquamarine", "royal", "midnight",
    "powder", "baby", "periwinkle", "denim", "slate",
    "emerald", "jade", "mint", "forest", "lime", "olive", "sea", "pine",
    "teal", "jungle", "sage", "hunter", "viridian", "chartreuse", "kelly",
    "shamrock", "malachite", "verdant",
    "gold", "amber", "ivory", "beige", "cream", "blonde", "champagne",
    "lemon", "mustard", "saffron", "sunflower", "daffodil", "butter",
    "corn", "honey", "goldenrod", "tangerine",
    "coral", "peach", "salmon", "apricot", "copper", "bronze", "rust",
    "burnt", "sienna", "pumpkin", "carrot", "ginger", "cinnamon",
    "violet", "lavender", "mauve", "magenta", "fuchsia", "plum", "orchid",
    "lilac", "periwinkle", "amethyst", "eggplant", "indigo", "heliotrope",
    "mulberry", "prune", "slate",
    "rose", "magenta", "fuchsia", "hot", "salmon", "coral", "blush",
    "carnation", "flamingo", "raspberry", "strawberry", "bubblegum",
    "cotton", "powder", "baby", "cherry",
    "brown", "tan", "beige", "khaki", "taupe", "camel", "sand", "bronze",
    "copper", "chocolate", "cocoa", "coffee", "sepia", "umber", "oak",
    "walnut", "pecan", "hazel", "almond",
    "black", "white", "gray", "grey", "silver", "charcoal", "ash", "smoke",
    "steel", "iron", "lead", "slate", "storm", "twilight", "jet", "onyx",
    "obsidian", "ebony", "ink",
    "gold", "silver", "bronze", "copper", "brass", "platinum", "steel",
    "chrome", "aluminum", "mercury", "iron", "lead", "zinc", "tin",
    "pastel", "powder", "misty", "soft", "washed", "pale", "light",
    "turquoise", "peacock", "peach", "apricot", "melon", "cantaloupe",
    "watermelon", "raspberry", "crimson", "cardinal", "blood", "wine",
    "burgundy", "claret", "maroon", "scarlet", "vermilion", "terracotta",
    "ochre", "sienna", "umber", "sepia", "turmeric", "saffron", "paprika"
]

favorite_animals = [
    "dog", "cat", "elephant", "lion", "tiger", "bear", "wolf", "fox",
    "deer", "rabbit", "squirrel", "mouse", "rat", "horse", "cow", "pig",
    "sheep", "goat", "monkey", "gorilla", "chimp", "kangaroo", "koala",
    "panda", "whale", "dolphin", "seal", "walrus", "bat", "human",
    "eagle", "hawk", "owl", "parrot", "eagle", "robin", "sparrow",
    "penguin", "ostrich", "emu", "pelican", "flamingo", "swan", "duck",
    "goose", "chicken", "turkey", "peacock", "dove", "crow", "raven",
    "salmon", "tuna", "shark", "goldfish", "clownfish", "eel", "trout",
    "bass", "pike", "mackerel", "cod", "herring", "sardine", "anchovy",
    "snake", "lizard", "turtle", "tortoise", "crocodile", "alligator",
    "iguana", "gecko", "chameleon", "python", "cobra", "rattlesnake",
    "frog", "toad", "salamander", "newt", "axolotl",
    "ant", "bee", "butterfly", "moth", "fly", "mosquito", "dragonfly",
    "grasshopper", "cricket", "spider", "scorpion", "centipede", "millipede",
    "beetle", "ladybug", "firefly", "wasp", "hornet", "termite",
    "octopus", "squid", "jellyfish", "starfish", "sea urchin", "coral",
    "crab", "lobster", "shrimp", "ray", "seahorse", "hippo",
    "platypus", "echidna", "sloth", "armadillo", "anteater", "lemur",
    "zebra", "giraffe", "hippopotamus", "rhinoceros", "cheetah", "leopard"
]

favorite_seasons = ['Spring', 'Summer', 'Autumn', 'Fall', 'Winter']

favorite_foods = [
    "pizza", "pasta", "lasagna", "spaghetti", "ravioli", "risotto", "gelato",
    "hamburger", "cheeseburger", "hot dog", "fried chicken", "steak", 
    "fried fish", "mac and cheese", "bbq ribs", "apple pie", "chocolate chip cookies",
    "sushi", "ramen", "fried rice", "chow mein", "pad thai", "kimchi", 
    "bulgogi", "curry", "dumplings", "spring rolls",
    "tacos", "burritos", "quesadillas", "enchiladas", "tamales", 
    "nachos", "guacamole", "salsa",
    "pancakes", "waffles", "french toast", "scrambled eggs", "bacon", 
    "sausage", "cereal", "oatmeal", "yogurt", "granola",
    "chocolate", "ice cream", "cake", "brownies", "cookies", "chips",
    "popcorn", "nuts", "fruit", "cheese", "bread", "sandwich",
    "soup", "stew", "potatoes", "fried potatoes", "pizza", "pasta",
    "chicken soup", "grilled cheese", "cornbread",
    "falafel", "hummus", "shawarma", "kebab", "paella", "crepes", 
    "croissants", "scones", "bagels", "dim sum",
    "salmon", "tuna", "shrimp", "lobster", "crab", "scallops",
    "salad", "vegetable stir fry", "quinoa bowl", "avocado toast",
    "hummus", "veggie burger"
]

political_side = [
    "Democratic Party", "Republican Party", "Libertarian Party",
    "Green Party", "Constitution Party", "Working Families Party",
    "Socialist Party", "Progressive Party", "Liberal", "Conservative",
    "Moderate", "Progressive", "Libertarian", "Socialist",
    "Democratic Socialist", "Populist", "Centrist",
    "Neoliberal", "Neoconservative", "Classical Liberal",
    "Social Liberal", "Fiscal Conservative", "Social Conservative", "Paleoconservative",
    "Reactionary", "Anarchist", "Communist", "Capitalist", "Federalist", "Anti-Federalist",
    "Whig", "Jacksonian Democrat", "Populist", "Progressive Era", "New Deal Democrat",
    "Reagan Republican", "Tea Party", "Occupy Movement", "Alt-Right", "Alt-Left",
    "Left-Wing", "Right-Wing", "Far-Left", "Far-Right", "Center-Left", "Center-Right",
    "Establishment", "Anti-Establishment"
]

email_providers = [
    'gmail.com', 'yahoo.com', 'outlook.com', 'hotmail.com', 'icloud.com', 'aol.com', 'protonmail.com',
    'zoho.com', 'mail.com', 'yandex.com', 'gmx.com', 'comcast.net', 'me.com', 'msn.com', 'mail.ru', 
    'live.com', 'rocketmail.com', 'fastmail.com', 'tutanota.com', 'hushmail.com', 'inbox.com', 
    'rediffmail.com', 'yahoo.co.uk', 'gmx.de', 'virmail.com', 'bluebottle.com', 'mailchimp.com', 
    'mac.com', 'seznam.cz', 'gawab.com', 'lycos.com', 'cableone.net', 'shaw.ca', 'virginmedia.com',
    'sbcglobal.net', 'att.net', 'earthlink.net', 'juno.com', 'netzero.net', 'optimum.net', 'bell.net',
    'cox.net', 'charter.net', 'fuse.net', 'epix.net', 'frontier.com', 'rcn.com', 'windstream.net',
    'mailinator.com', 'temp-mail.org', 'guerrillamail.com', '10minutemail.com', 'yopmail.com', 
    'dispostable.com', 'trashmail.com', 'spambox.us', 'spamex.com', 'maildrop.cc', 'throwawaymail.com',
    'spamgourmet.com', 'mailcatch.com', 'getnada.com', 'tempinbox.com', 'dodgit.com', 'fakeinbox.com',
    'mailnesia.com', 'inbox.lv', 'simplicmail.com', 'zapto.org', 'myself.com', 'tutanota.de', 'mailfence.com'
]


car = [
    "Toyota Camry", "Honda Civic", "Ford F-150", "Chevrolet Silverado", "Nissan Altima",
    "Hyundai Elantra", "Kia Soul", "Subaru Outback", "Mazda CX-5", "Volkswagen Jetta",
    "BMW 3 Series", "Mercedes C-Class", "Audi A4", "Lexus ES", "Infiniti Q50",
    "Acura TLX", "Cadillac CT5", "Genesis G80", "Tesla Model 3", "Tesla Model S",
    "Tesla Model X", "Tesla Model Y", "Ford Mustang", "Chevrolet Corvette", "Dodge Challenger",
    "Ford Explorer", "Chevrolet Equinox", "Jeep Grand Cherokee", "Toyota RAV4", "Honda CR-V",
    "Subaru Forester", "Mazda CX-9", "Volkswagen Tiguan", "Nissan Rogue", "Hyundai Santa Fe",
    "Kia Sorento", "Ford Escape", "Chevrolet Traverse", "Jeep Wrangler", "Toyota 4Runner",
    "Honda Pilot", "GMC Yukon", "Chevrolet Tahoe", "Ford Expedition", "Lincoln Navigator",
    "BMW X3", "Mercedes GLC", "Audi Q5", "Lexus RX", "Infiniti QX60", "Acura MDX",
    "Cadillac Escalade", "Lincoln Aviator", "Volvo XC90", "Volvo XC60", "Porsche Macan",
    "Porsche Cayenne", "Land Rover Range Rover", "Land Rover Discovery", "Jaguar F-Pace",
    "Alfa Romeo Giulia", "Maserati Ghibli", "Lamborghini Huracan", "Ferrari 488", "McLaren 720S",
    "Aston Martin DB11", "Bentley Continental", "Rolls-Royce Phantom", "Maybach S-Class",
    "BMW 5 Series", "Mercedes E-Class", "Audi A6", "Lexus GS", "Infiniti Q70", "Acura RLX",
    "Cadillac CT6", "Genesis G90", "BMW 7 Series", "Mercedes S-Class", "Audi A8", "Lexus LS",
    "Toyota Prius", "Honda Insight", "Hyundai Ioniq", "Kia Niro", "Chevrolet Bolt", "Nissan Leaf",
    "BMW i3", "Volkswagen ID.4", "Ford Focus", "Mazda3", "Nissan Sentra", "Hyundai Accent",
    "Kia Rio", "Chevrolet Malibu", "Ford Fusion", "Dodge Charger", "Subaru Impreza",
    "Volkswagen Golf", "Mini Cooper", "Fiat 500", "Smart Fortwo", "Mazda MX-5 Miata",
    "Chevrolet Camaro", "Ford GT", "Dodge Viper", "Chevrolet Silverado HD", "Ford Super Duty",
    "Ram 1500", "GMC Sierra", "Chevrolet Colorado", "Ford Ranger", "Toyota Tacoma",
    "Nissan Titan", "Honda Accord", "Toyota Corolla", "Nissan Maxima", "Hyundai Sonata",
    "Kia Optima", "Subaru Legacy", "Mazda6", "Volkswagen Passat", "Ford Taurus",
    "Buick LaCrosse", "Chrysler 300", "Dodge Magnum", "Pontiac Grand Prix", "Oldsmobile Intrigue",
    "Saturn Aura", "Suzuki Swift", "Mitsubishi Lancer", "Eagle Talon", "Plymouth Neon",
    "Mercury Sable", "Lincoln Continental", "Cadillac DeVille", "Buick Century", "Oldsmobile Cutlass",
    "Pontiac Grand Am", "Chevrolet Lumina", "Ford Crown Victoria", "Mercury Grand Marquis",
    "Dodge Intrepid", "Chrysler Concorde", "Eagle Vision", "Plymouth Acclaim", "Dodge Stealth",
    "Acura Legend", "Infiniti J30", "Nissan 300ZX", "Mazda RX-7", "Mitsubishi 3000GT",
    "Toyota Supra", "Nissan 240SX", "Honda Prelude", "Acura Integra", "Mazda MX-6",
    "Ford Probe", "Chevrolet Beretta", "Pontiac Firebird", "Toyota Celica", "Mazda 626",
    "Subaru SVX", "Volkswagen Corrado", "Ford Bronco", "Chevrolet Blazer", "Isuzu Trooper",
    "Mazda Navajo", "Plymouth Voyager", "Dodge Caravan", "Chrysler Town & Country", "Pontiac Trans Sport",
    "Mercury Villager", "Nissan Quest", "Toyota Previa", "Honda Odyssey", "Mitsubishi Expo",
    "Suzuki Sidekick", "Geo Tracker", "Isuzu Amigo", "Mazda B-Series", "Ford Aerostar",
    "Chevrolet Astro", "GMC Safari", "Nissan Vanette", "Toyota Van", "Chrysler Voyager",
    "Dodge Ram Van", "Ford E-Series", "Chevrolet Express", "GMC Savana", "Mercedes Sprinter",
    "Fiat Ducato", "Renault Master", "Peugeot Boxer", "Citroën Jumper", "Volkswagen Crafter",
    "Ford Transit", "Mercedes Vito", "Volkswagen Transporter", "Fiat Scudo", "Opel Vivaro",
    "BMW X5", "Mercedes GLE", "Audi Q7", "Lexus GX", "Infiniti QX80", "Acura RDX",
    "Cadillac XT5", "Lincoln MKX", "Volvo V90", "Volvo V60", "Porsche Panamera",
    "Porsche 911", "Ferrari F8", "Lamborghini Aventador", "Maserati Levante", "Aston Martin DBX",
    "Bentley Bentayga", "Rolls-Royce Cullinan", "Maybach GLS", "BMW X7", "Mercedes GLS",
    "Audi Q8", "Lexus LX", "Toyota Sequoia", "Nissan Armada", "Subaru Ascent",
    "Honda HR-V", "Kia Sportage", "Hyundai Kona", "Mazda CX-3", "Volkswagen Atlas",
    "Ford Edge", "Chevrolet Trax", "Buick Encore", "Cadillac XT4", "Lincoln Corsair",
    "Volvo S90", "Volvo S60", "Alfa Romeo Stelvio", "Fiat 500X", "Jeep Compass",
    "Mitsubishi Outlander", "Suzuki Equator", "Isuzu Ascender", "Saab 9-3", "Opel Astra",
    "Holden Commodore", "HSV Maloo", "Lotus Elise", "TVR Sagaris", "Morgan Plus 8",
    "Caterham 7", "Noble M600", "RUF CTR", "Spyker C8", "Koenigsegg Agera",
    "Pagani Huayra", "Bugatti Chiron", "Rimac Concept", "Tesla Roadster", "Polestar 2",
    "Lucid Air", "Rivian R1T", "Ford Mustang Mach-E", "Chevrolet Silverado EV", "GMC Hummer EV",
    "Nissan Ariya", "Hyundai Ioniq 5", "Kia EV6", "BMW iX", "Mercedes EQS",
    "Audi e-tron", "Porsche Taycan", "Genesis GV60", "Volvo C40", "Subaru Solterra",
    "Toyota bZ4X", "Honda Prologue", "Cadillac Lyriq", "Lincoln Star", "Mercedes EQE",
    "BMW i4", "Audi Q4 e-tron", "Volkswagen ID. Buzz", "Fiat 500e", "Mini Cooper SE",
    "Hyundai Ioniq 6", "Genesis Electrified GV70", "BMW X1", "Mercedes GLB", "Audi Q3",
    "Lexus UX", "Infiniti QX50", "Acura ILX", "Cadillac ATS", "Lincoln MKZ",
    "Volvo S80", "Alfa Romeo 4C", "Fiat 124 Spider", "Mazda MX-30", "Subaru BRZ",
    "Toyota GR86", "Chevrolet Corvette Stingray", "Ford Shelby GT500", "Dodge Durango",
    "Jeep Gladiator", "Toyota Land Cruiser", "Nissan Patrol", "Mercedes G-Class",
    "Land Rover Defender", "Porsche 911 Turbo", "Ferrari Roma", "Lamborghini Urus",
    "Maserati Quattroporte", "Aston Martin Vantage", "Bentley Flying Spur",
    "Rolls-Royce Ghost", "Maybach S650", "BMW M3", "Mercedes AMG GT", "Audi RS6",
    "Lexus RC F", "Infiniti Q60 Red Sport", "Acura NSX", "Cadillac CTS-V", "Lincoln Continental",
    "Volvo XC40", "Alfa Romeo Giulietta", "Fiat Panda", "Jeep Renegade", "Mitsubishi Eclipse Cross",
    "Suzuki Vitara", "Isuzu D-Max", "MG ZS", "Lynk & Co 01", "Geely Preface",
    "Proton X70", "Perodua Axia", "Tata Nexon", "Mahindra XUV500", "Kia Stinger",
    "Genesis GV80", "Volvo P1800", "Saab 900", "Opel Kadett", "Holden Monaro",
    "HSV GTS", "Lotus Elan", "TVR Griffith", "Morgan Roadster", "Caterham Super Seven",
    "Noble M400", "RUF Rt 12", "Spyker D8", "Koenigsegg CCXR", "Pagani Zonda",
    "Bugatti Veyron", "Rimac Nevera", "Tesla Cybertruck", "Polestar 3", "Lucid Gravity",
    "Rivian R1S", "Ford Lightning", "Chevrolet Equinox EV", "GMC Sierra EV", "Nissan Ariya EV",
    "Hyundai Ioniq 7", "Kia EV9", "BMW Neue Klasse", "Mercedes EQB", "Audi A5 Sportback"
]

###########################################################################################################################################################################

street_names = [
    'Main Street', 'First Street', 'Second Street', 'Third Street', 'Elm Street', 'Oak Street', 'Pine Street',
    'Maple Street', 'Washington Street', 'Broadway', 'High Street', 'Park Avenue', 'King Street', 'Church Street',
    'Cedar Street', 'River Road', 'Lake Road', 'Sunset Boulevard', 'North Avenue', 'South Avenue', 'East Road',
    'West Road', 'Hill Street', 'Monroe Street', 'Jefferson Street', 'Franklin Street', 'Adams Street', 'Lincoln Street',
    'State Street', 'Victory Road', 'Rose Street', 'Baker Street', 'Pleasant Street', 'Green Street', 'Spring Street',
    'Woods Road', 'Sunnyvale Road', 'Cottonwood Drive', 'Independence Avenue', 'Heritage Way', 'Hilltop Drive',
    'Ridge Road', 'Country Road', 'Sunshine Street', 'Silver Avenue', 'Golden Drive', 'Main Avenue', 'Kingston Road',
    'Broadway Avenue', 'Peachtree Street', 'Lakeside Drive', 'Shady Lane', 'Oakwood Drive', 'Rainbow Boulevard',
    'Cherry Blossom Drive', 'Cypress Street', 'Sunset Drive', 'Sierra Avenue', 'Mountain View Road', 'Water Street',
    'Pinehurst Drive', 'Clearview Street', 'Bluebell Road', 'Hawthorne Avenue', 'Riverfront Road', 'Wellington Drive',
    'Summit Street', 'Miller Road', 'Maple Avenue', 'Redwood Street', 'Tanglewood Drive', 'Linden Street', 'Ash Street',
    'Briargate Road', 'New Hope Road', 'Parkwood Drive', 'Thornhill Street', 'Windsor Road', 'Chestnut Street',
    'Hickory Lane', 'Crescent Avenue', 'Valley Road', 'Sunrise Boulevard', 'Silver Oak Drive', 'Rolling Hills Road',
    'Riverstone Lane', 'Belfast Road', 'Bristol Drive', 'Cottonwood Avenue', 'Chestnut Avenue', 'Glenwood Road',
    'Silver Creek Drive', 'Eagle Street', 'Springdale Road', 'Copperstone Drive', 'Mountain View Drive', 'Beach Street']

cities = [
    'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 
    'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 'San Francisco',
    'Charlotte', 'Indianapolis', 'Seattle', 'Denver', 'Washington D.C.', 'Boston', 'El Paso', 
    'Detroit', 'Nashville', 'Portland', 'Memphis', 'Oklahoma City', 'Las Vegas', 'Louisville', 
    'Baltimore', 'Milwaukee', 'Albuquerque', 'Tucson', 'Fresno', 'Mesa', 'Sacramento', 'Kansas City', 
    'Long Beach', 'Atlanta', 'Colorado Springs', 'Raleigh', 'Miami', 'Omaha', 'Oakland', 'Minneapolis',
    'Tulsa', 'Wichita', 'Arlington', 'New Orleans', 'Cleveland', 'Bakersfield', 'Tampa', 'Henderson', 
    'Aurora', 'Honolulu', 'Anaheim', 'Santa Ana', 'Riverside', 'Corpus Christi', 'Lexington', 'St. Louis', 
    'Stockton', 'Pittsburgh', 'St. Paul', 'Cincinnati', 'Anchorage', 'Greensboro', 'Plano', 'Newark', 
    'Lincoln', 'Orlando', 'Irvine', 'Toledo', 'Jersey City', 'Chula Vista', 'Durham', 'Fort Wayne', 
    'Buffalo', 'Madison', 'Lubbock', 'Chandler', 'Glendale', 'Reno', 'Norfolk', 'Winston-Salem', 'Gilbert', 
    'Hialeah', 'Arlington', 'Huntington Beach', 'Montgomery', 'Boise', 'Richmond', 'Des Moines', 
    'Spokane', 'Tacoma', 'San Bernardino', 'Modesto', 'Fontana', 'Santa Clarita', 'Birmingham', 
    'Oxnard', 'Fayetteville', 'Moreno Valley', 'Shreveport', 'Aurora', 'Yonkers', 'Columbia', 'Lakewood',
    'Cape Coral', 'Peoria', 'Jackson', 'Naperville', 'Escondido', 'Fullerton', 'McKinney', 'Killeen', 
    'Bellevue', 'Rockford', 'McAllen', 'Costa Mesa', 'Inglewood', 'Manchester', 'Waterbury', 'Charleston',
    'West Valley City', 'Lewisville', 'Huntington', 'Gresham', 'Fargo', 'Glendale', 'South Bend', 'Edmond',
    'Columbus', 'Round Rock', 'Nampa', 'Shreveport', 'Lafayette', 'Baton Rouge', 'Tallahassee', 
    'Tempe', 'Chattanooga', 'Syracuse', 'Albany', 'Denton', 'Allentown', 'Lansing', 'Evansville', 'Toledo', 
    'Pueblo', 'Chico', 'Bend', 'Springfield', 'Cedar Rapids', 'Tallahassee', 'Lincoln', 'Overland Park']
states = ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY']








def choose_gender():
    gender_choice = input("[!] Please choose a gender (Male/Female): ")
    if gender_choice == "Male":
        gender = "Male"
    elif gender_choice == "Female":
        gender = "Female"
    else:
        print("[ERROR] Invalid choice! Please select 'Male' or 'Female'.")
        return choose_gender()
    return gender
chosen_gender = choose_gender()
print(f"[INFO] The selected gender is: {chosen_gender}")

def generate_random_birthday():
    today = datetime.today()
    age_range_start = 18
    age_range_end = 100
    age = random.randint(age_range_start, age_range_end)
    birth_year = today.year - age
    random_month = random.randint(1, 12)
    days_in_month = [31, 29 if (birth_year % 4 == 0 and (birth_year % 100 != 0 or birth_year % 400 == 0)) else 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]
    random_day = random.randint(1, days_in_month[random_month - 1])
    random_birthday = datetime(birth_year, random_month, random_day)
    return random_birthday, age
birthday, age = generate_random_birthday()

def get_random_item(item_list):
    return random.choice(item_list)

def generate_driver_license():
    state = random.choice(states)
    number_length = random.randint(7,9)
    number = ''.join(random.choices(string.digits, k=number_length))
    letter_suffix = ''.join(random.choices(string.ascii_uppercase, k=random.randint(1, 2)))
    license_number = f"{state}-{number}-{letter_suffix}"
    return license_number
random_license = generate_driver_license() 
    
def generate_random_address():
    state = random.choice(states)
    city = random.choice(cities)
    street_number = random.randint(100, 9999)
    street_name = random.choice(street_names)
    street_address = f"{street_number} {street_name} St."
    zip_code = random.randint(10000, 99999)
    address = f"{street_address} {city}, {state} {zip_code}"
    return address
random_address = generate_random_address()

def generate_random_person():
    if chosen_gender == 'Male':
        first_name = get_random_item(first_names_male)
        middle_name = get_random_item(male_middle_names)
    else:
        first_name = get_random_item(first_names_female)
        middle_name = get_random_item(female_middle_names)
    last_name = get_random_item(last_names)
    full_name = f"{first_name} {middle_name} {last_name}"
    return {
        print("\n====PERSONAL INFORMATION===="),
        print(f"Name: {full_name}"),
        print(f"Gender: {chosen_gender}"),
        print(f"Birthday: {birthday.strftime('%B %d, %Y')} (Age: {age})"),
        print(f"Birthplace: {get_random_item(cities)}, USA"),
        print(f"Phone: ({random.randint(100,999)})-{random.randint(200,999)}-{random.randint(1000,9999)}"),
        print(f"Social Security Number (SSN): {random.randint(100, 999)}-{random.randint(10, 99)}-{random.randint(1000,9999)}"),
        print(f"Address: {random_address}"),
        print(f"Ziodiac sign: {get_random_item(ziodiac_sign)}"),
        print(f"E-mail: {first_name.lower()}{last_name.lower()}@{get_random_item(email_providers)}"),
        print(f"Driver license: {random_license}"),
        print(f"Car: {get_random_item(car)}"),
        print('\n====PHYSICAL APPEARANCE===='),
        print(f"Hair color: {get_random_item(hair_color)}"),
        print(f"Eyes color: {get_random_item(eyes_color)}"),
#        print(f"Height: {random.randint(0, 1)}, {random.ranadint(0, 99)}"),
        print(f"Weight: {random.randint(45, 100)}kg"),
        print(f"Shoe size: {random.randint(5, 20)}"),
        print(f"Blood type: {get_random_item(blood_type)}"),
        print('\n====PERSONALITY===='),
        print(f"Religion: {get_random_item(religion)}"),
        print(f"Political side: {get_random_item(political_side)}"),
        print(f"Favorite color: {get_random_item(favorite_color)}"),
        print(f"Favorite cereal: {get_random_item(favorite_cereals)}"),
        print(f"Favorite season: {get_random_item(favorite_seasons)}"),
        print(f"Favorite animal: {get_random_item(favorite_animals)}"),
        print(f"Lucky number: {random.randint(0, 99)}")
    }

person = generate_random_person()
print(person)
